// Rink registry.
//
// Every rink has a `state` code from STATES. A state's `slug` is its web address
// (calarink.com/maine); the build writes a page for each one.
//
// source.type:
//   'ics'      – iCalendar feed (public Google Calendars work: .../calendar/ical/<id>/public/basic.ics)
//   'finnly'   – Finnly Connect public schedule page
//   'pageText' – schedule posted as text on a web page (dated lines, optional weekly lines)
//   'daysmart' – DaySmart Recreation (Dash) booking API
//   'courtreserve' – CourtReserve public calendar; `categories` picks the ice categories by name
//   none       – no machine-readable schedule; shown as a "check directly" card
//
// To add a rink, append an entry. `id` must be unique and stable (it's used in the URL filters).

const gcal = id => `https://calendar.google.com/calendar/ical/${encodeURIComponent(id)}/public/basic.ics`;

// City-wide schedules that serve many arenas; each arena picks out its own sessions.
const toronto = locationId => [{ type: 'torontoDropIn', locationId }];
const montreal = slug => [{ type: 'montrealArena', url: `https://montreal.ca/lieux/${slug}` }];
const calgary = venue => [{
  type: 'classList', base: 'https://liveandplay.calgary.ca/REGPROG', venue, exclude: /goalies/i,
  categories: ['86b5d1d9-687a-40b2-aa48-f5a296b7fe13', 'edd094c5-1190-44d4-a20e-5d152e812e06'], // Public Skate, Shinny
}];
const vancouver = centerId => [{
  type: 'activenet', site: 'https://anc.ca.apm.activecommunities.com/vancouver', calendarId: 3, centerId, exclude: /goalies/i,
}];

// `tz` is the state's time zone: schedules that give local times are read in it, and the
// site shows that state's times in it. `default` is the state a first-time visitor sees.
// Canadian provinces are listed the same way, with `country: 'CA'` (US is the default).
export const STATES = [
  { code: 'CO', slug: 'colorado', name: 'Colorado', tz: 'America/Denver' },
  { code: 'CT', slug: 'connecticut', name: 'Connecticut', tz: 'America/New_York' },
  { code: 'FL', slug: 'florida', name: 'Florida', tz: 'America/New_York' },
  { code: 'ME', slug: 'maine', name: 'Maine', tz: 'America/New_York', default: true },
  { code: 'MA', slug: 'massachusetts', name: 'Massachusetts', tz: 'America/New_York' },
  { code: 'MI', slug: 'michigan', name: 'Michigan', tz: 'America/Detroit' },
  { code: 'MN', slug: 'minnesota', name: 'Minnesota', tz: 'America/Chicago' },
  { code: 'NH', slug: 'new-hampshire', name: 'New Hampshire', tz: 'America/New_York' },
  { code: 'NY', slug: 'new-york', name: 'New York', tz: 'America/New_York' },
  { code: 'RI', slug: 'rhode-island', name: 'Rhode Island', tz: 'America/New_York' },
  { code: 'VT', slug: 'vermont', name: 'Vermont', tz: 'America/New_York' },
  { code: 'AB', slug: 'alberta', name: 'Alberta', tz: 'America/Edmonton', country: 'CA' },
  { code: 'BC', slug: 'british-columbia', name: 'British Columbia', tz: 'America/Vancouver', country: 'CA' },
  { code: 'MB', slug: 'manitoba', name: 'Manitoba', tz: 'America/Winnipeg', country: 'CA' },
  { code: 'NB', slug: 'new-brunswick', name: 'New Brunswick', tz: 'America/Moncton', country: 'CA' },
  { code: 'NL', slug: 'newfoundland-and-labrador', name: 'Newfoundland and Labrador', tz: 'America/St_Johns', country: 'CA' },
  { code: 'NS', slug: 'nova-scotia', name: 'Nova Scotia', tz: 'America/Halifax', country: 'CA' },
  { code: 'ON', slug: 'ontario', name: 'Ontario', tz: 'America/Toronto', country: 'CA' },
  { code: 'PE', slug: 'prince-edward-island', name: 'Prince Edward Island', tz: 'America/Halifax', country: 'CA' },
  { code: 'QC', slug: 'quebec', name: 'Québec', tz: 'America/Toronto', country: 'CA' },
  { code: 'SK', slug: 'saskatchewan', name: 'Saskatchewan', tz: 'America/Regina', country: 'CA' },
];

export const RINKS = [
  {
    id: 'usm-gorham',
    name: 'USM Ice Arena',
    town: 'Gorham', state: 'ME', region: 'Southern',
    website: 'https://usm.maine.edu/ice-arena/hours/',
    sources: [{ type: 'ics', url: gcal('usmicearena@maine.edu') }],
    note: 'Full arena calendar. "Student Open Skate" is USM-only.',
  },
  {
    id: 'ice-vault-hallowell',
    name: 'Thomas College Ice Vault',
    town: 'Hallowell', state: 'ME', region: 'Central',
    address: '203 Whitten Rd, Hallowell, ME',
    website: 'https://www.maineicevault.com/',
    scheduleUrl: 'https://tciv.finnlyconnect.com/schedule/612',
    sources: [{ type: 'finnly', url: 'https://tciv.finnlyconnect.com/schedule/612' }],
    note: 'Public skate $10, rentals $6. Weekend sessions often sell out — buy online.',
  },
  {
    id: 'alfond-orono',
    name: 'Alfond Arena (UMaine)',
    town: 'Orono', state: 'ME', region: 'Northern & Downeast',
    website: 'https://umaine.edu/campusrecreation/facilities__trashed/alfond-arena/',
    sources: [{ type: 'ics', url: gcal('o84kduv0jjtn8siju6nu5i9ueg@group.calendar.google.com') }],
    note: 'Public skate & stick-and-puck calendar only (Campus Rec). Stick & Puck is 18+.',
  },
  {
    id: 'pia-brewer',
    name: 'Penobscot Ice Arena (PIA)',
    town: 'Brewer', state: 'ME', region: 'Northern & Downeast',
    address: '90 Acme Rd, Brewer, ME', phone: '207-989-7183',
    website: 'https://www.penobscoticearena.com/',
    sources: [{ type: 'ics', url: gcal('m3mm3gbf0u02ko5jcg9r7c091k@group.calendar.google.com') }],
    note: 'Full arena calendar. Some stick n puck sessions are age-split (13 & under / 14 & over).',
  },
  {
    id: 'pcia-dover-foxcroft',
    name: 'Piscataquis County Ice Arena (PCIA)',
    town: 'Dover-Foxcroft', state: 'ME', region: 'Northern & Downeast',
    address: '1049 W Main St, Dover-Foxcroft, ME',
    website: 'https://www.thepcia.com/public-skate.html',
    scheduleUrl: 'https://pcia.finnlyconnect.com/schedule/903',
    sources: [{ type: 'finnly', url: 'https://pcia.finnlyconnect.com/schedule/903' }],
    note: 'Public skate $10, walk-ins welcome; skate rental $3. "Stick Time" is their stick & puck.',
  },
  {
    id: 'forum-presque-isle',
    name: 'The Forum',
    town: 'Presque Isle', state: 'ME', region: 'Northern & Downeast',
    phone: '207-764-0491',
    website: 'https://www.thepiforum.org/',
    sources: [{ type: 'ics', url: 'https://outlook.office365.com/owa/calendar/0069475393ca4306b04019da8c33ab28@presqueisleme.us/815093ea02cb4d868f4e76c2f0ebcc8c8151721194698282749/calendar.ics' }],
    note: 'Full arena calendar (City of Presque Isle Outlook calendar). Public skate $7, rentals $5. Times can change for hockey games — call to confirm.',
  },
  {
    id: 'casco-bay-falmouth',
    name: 'Casco Bay Arena',
    town: 'Falmouth', state: 'ME', region: 'Southern',
    website: 'https://cascobayarena.com/ice-schedule-2/',
    sources: [{ type: 'ics', url: gcal('12qbntcc8t3cgl39lde3pm54ao@group.calendar.google.com') }],
    note: 'Arena master schedule. Mostly team ice; "OPEN" = unbooked ice, not a public session.',
  },
  {
    id: 'nsb-auburn',
    name: 'Norway Savings Bank Arena',
    town: 'Auburn', state: 'ME', region: 'Central',
    address: '985 Turner St, Auburn, ME',
    website: 'https://www.norwaysavingsbankarena.com/page/show/8447987-drop-in-recreational-programming',
    sources: [
      { type: 'pageText', title: 'Public Skate', url: 'https://www.norwaysavingsbankarena.com/page/show/7694782-public-skate-', projectWeekly: 6 },
      { type: 'pageText', title: 'Shinny Hockey', url: 'https://www.norwaysavingsbankarena.com/page/show/8023693-shinny-hockey-schedule-' },
    ],
    note: 'Read from the arena\'s posted text. Public skate $5; shinny $10. Changes often — check the site.',
  },

  {
    id: 'midcoast-rockport',
    name: 'Midcoast Recreation Center',
    town: 'Rockport', state: 'ME', region: 'Midcoast',
    address: '535 West St, Rockport, ME', phone: '207-236-9400',
    website: 'https://www.midcoastrec.org/public-skate',
    scheduleUrl: 'https://book.midcoastrec.org/Online/Public/EmbedCode/16147/58434?customId=125636',
    sources: [{
      type: 'courtreserve',
      url: 'https://book.midcoastrec.org/Online/Public/EmbedCode/16147/58434?customId=125636',
      categories: /hockey|skat/i, // the calendar also carries tennis, pickleball, golf and fitness
      exclude: /off-ice (only|training)/i,
    }],
    note: "Ice programs from the club calendar (hockey, figure skating and skating categories). Arena rentals aren't shown.",
  },

  // ---- No machine-readable schedule: shown as "check directly" ----
  {
    id: 'troubh-portland',
    name: 'Troubh Ice Arena',
    town: 'Portland', state: 'ME', region: 'Southern',
    address: '225 Park Ave, Portland, ME', phone: '207-774-8553',
    website: 'https://www.portlandmaine.gov/528/William-B-Troubh-Ice-Arena',
    note: 'Public skate calendar is posted as a monthly PDF.',
  },
  {
    id: 'colisee-lewiston',
    name: 'The Colisée',
    town: 'Lewiston', state: 'ME', region: 'Central',
    address: '190 Birch St, Lewiston, ME', phone: '207-783-2009',
    website: 'https://www.thecolisee.com/',
  },
  {
    id: 'sawyer-bangor',
    name: 'Sawyer Arena',
    town: 'Bangor', state: 'ME', region: 'Northern & Downeast',
    address: '107 13th St, Bangor, ME', phone: '207-947-0071',
    website: 'https://www.bangormaine.gov/676/Sawyer-Arena',
    note: 'Closed for the off-season; reopens October 2026. Public skate times are posted as PDFs on Bangor Parks & Rec (bangorme.myrec.com) and Facebook.',
  },
  {
    id: 'biddeford',
    name: 'Biddeford Ice Arena',
    town: 'Biddeford', state: 'ME', region: 'Southern',
    address: '14 Pomerleau St, Biddeford, ME', phone: '207-283-0615',
    website: 'https://biddefordarena.com/public-skating',
    note: 'Public skating is limited; they post times on Facebook.',
  },
  {
    id: 'family-ice-falmouth',
    name: 'Family Ice Center',
    town: 'Falmouth', state: 'ME', region: 'Southern',
    address: '20 Hat Trick Dr, Falmouth, ME', phone: '207-781-4200',
    website: 'https://familyice.org/programs/public-skating/',
    note: 'Outdoor pond only, early Dec – late Feb, 10am–9pm daily, weather permitting. Free. No indoor public skate.',
  },
  {
    id: 'travis-roy-yarmouth',
    name: 'Travis Roy Ice Arena (NYA)',
    town: 'Yarmouth', state: 'ME', region: 'Southern',
    website: 'https://www.facebook.com/NYATravisRoyArena/',
  },
  {
    id: 'thompsons-point',
    name: "The Rink at Thompson's Point (outdoor, seasonal)",
    town: 'Portland', state: 'ME', region: 'Southern',
    website: 'https://www.thompsonspointrink.com/iceschedule',
  },

  // ================= Massachusetts =================
  {
    id: 'warrior-boston',
    name: 'Warrior Ice Arena',
    town: 'Boston (Brighton)', state: 'MA', region: 'Boston Area',
    address: '90 Guest St, Boston, MA',
    website: 'https://www.warrioricearena.com/public-sessions/',
    scheduleUrl: 'https://warrior.finnlyconnect.com/schedule/19',
    sources: [{ type: 'finnly', url: 'https://warrior.finnlyconnect.com/schedule/19' }],
    note: 'Bruins practice facility. Public skate $16 weekdays, $18 weekends (skate rental included).',
  },
  {
    id: 'canton-ice-house',
    name: 'Canton Ice House',
    town: 'Canton', state: 'MA', region: 'South Shore & South',
    website: 'https://www.cantonicehouse.com/',
    scheduleUrl: 'https://cih.finnlyconnect.com/schedule/594',
    sources: [{ type: 'finnly', url: 'https://cih.finnlyconnect.com/schedule/594' }],
    note: 'Full arena schedule. Mostly team ice; freestyle sessions are listed.',
  },
  {
    id: 'rodman-walpole',
    name: 'Rodman Arena',
    town: 'Walpole', state: 'MA', region: 'South Shore & South',
    address: '2130 Providence Hwy, Walpole, MA',
    website: 'https://www.rodmanarena.com/',
    sources: [
      { type: 'ics', url: gcal('d6367ea5971e44b01054cd0be45b3d31d51750301807bea35a4222fd0e3455ec@group.calendar.google.com') },
      { type: 'ics', url: gcal('0e071d4ca0f264df1bdf6ef6a5507f0771ac06655475640e3d52f1772be234dc@group.calendar.google.com') },
    ],
    note: 'Public skating $7 adults, $5 under 10. Public hockey $8, ages 14+, helmet and gloves required.',
  },
  {
    id: 'talbot-gloucester',
    name: 'Talbot Rink',
    town: 'Gloucester', state: 'MA', region: 'North Shore',
    address: '31 Cherry St, Gloucester, MA',
    website: 'https://talbotrink.gloucester-ma.gov/',
    sources: [{ type: 'ics', url: gcal('c_5sfgegqoa0900b84c6alefte18@group.calendar.google.com') }],
    note: 'Full rink calendar. Public skating Sundays, mid-November through March; adult stick practice and adult skate Wednesday mornings.',
  },
  {
    id: 'stoneham-arena',
    name: 'Stoneham Arena',
    town: 'Stoneham', state: 'MA', region: 'Boston Area',
    website: 'https://www.stoneham-ma.gov/164/Stoneham-Arena',
    note: 'Public skating, adult stick practice and freestyle. Stick practice and freestyle require pre-registration by email.',
  },
  {
    id: 'edge-bedford',
    name: 'The Edge Sports Center',
    town: 'Bedford', state: 'MA', region: 'Boston Area',
    address: '191 Hartwell Ave, Bedford, MA',
    website: 'https://theedgesportscenter.com/services/public-skating/',
  },
  {
    id: 'pilgrim-hingham',
    name: 'Pilgrim Skating Arena',
    town: 'Hingham', state: 'MA', region: 'South Shore & South',
    address: '75 Recreation Park Dr, Hingham, MA',
    website: 'https://www.pilgrimarena.com/',
  },
  {
    id: 'olympia-west-springfield',
    name: 'Olympia Ice Center',
    town: 'West Springfield', state: 'MA', region: 'Western',
    website: 'https://www.olympiaicecenter.com/',
  },
  {
    id: 'dcr-rinks',
    name: 'DCR state rinks',
    town: 'Statewide', state: 'MA', region: 'Boston Area',
    website: 'https://www.mass.gov/info-details/dcr-ice-skating-rink-schedule',
    note: 'The state runs about 15 rinks, mostly around Boston. Public skating runs late November to mid-April, with public stick time at some rinks. Hours for each rink are on this page.',
  },

  // ================= New Hampshire =================
  {
    id: 'everett-concord',
    name: 'Everett Arena',
    town: 'Concord', state: 'NH', region: 'Central & Lakes',
    website: 'https://concordnh.gov/921/Ice-Skating-Stick-Practice',
    scheduleUrl: 'https://everett.finnlyconnect.com/schedule/1005',
    sources: [{ type: 'finnly', url: 'https://everett.finnlyconnect.com/schedule/1005' }],
    note: 'City-run. Season mid-September to mid-March. Stick practice is also offered; check the city page for hours.',
  },
  {
    id: 'keene-ice',
    name: 'Keene Ice',
    town: 'Keene', state: 'NH', region: 'West & North',
    website: 'https://www.keeneice.com/',
    scheduleUrl: 'https://keene.finnlyconnect.com/schedule/91',
    sources: [{ type: 'finnly', url: 'https://keene.finnlyconnect.com/schedule/91' }],
    note: 'Public skate $8, rentals $5. Adult stick time $12, full gear required.',
  },
  {
    id: 'campion-hanover',
    name: 'Campion Rink',
    town: 'Hanover', state: 'NH', region: 'West & North',
    website: 'https://www.campionrink.org/',
    sources: [{ type: 'daysmart', company: 'hanover' }],
    note: 'Full rink schedule. "Open Stick" is their stick & puck.',
  },
  {
    id: 'merrill-fay-laconia',
    name: 'Merrill Fay Arena',
    town: 'Laconia', state: 'NH', region: 'Central & Lakes',
    address: '468 Province Rd, Laconia, NH',
    website: 'https://merrillfayarena.com/',
    note: 'Public skating Saturdays and Sundays, 2:00–3:30 PM, from September. Also stick and puck and "Power Hour".',
  },
  {
    id: 'ham-arena-conway',
    name: 'Ham Arena',
    town: 'Conway', state: 'NH', region: 'West & North',
    website: 'https://hamarena.com/public-hours/',
    note: 'Non-profit rink. Public skating and stick & puck every week; schedules linked from this page.',
  },
  {
    id: 'conway-arena-nashua',
    name: 'Conway Arena',
    town: 'Nashua', state: 'NH', region: 'Southern',
    website: 'https://conwayarena.com/',
    note: 'Public skate, stick practice and freestyle; buy admission online.',
  },
  {
    id: 'jfk-manchester',
    name: 'JFK Coliseum',
    town: 'Manchester', state: 'NH', region: 'Southern',
    website: 'https://www.manchesternh.gov/Departments/Parks-and-Recreation/Programs-and-Activities/Activities/Ice-Skating',
    note: 'City-run. Public skating generally Tuesday and Thursday mornings and weekend afternoons, October–March. Stick & puck is at West Side Arena.',
  },

  // ================= Rhode Island =================
  {
    id: 'cvm-cranston',
    name: 'Cranston Veterans Memorial Rink',
    town: 'Cranston', state: 'RI', region: 'Providence Area',
    website: 'https://www.cvmrink.com/public',
    sources: [
      { type: 'ics', url: gcal('a2f5d1296a00a288bae699cf743e11f902fcba21604427a2d38421ed059720c2@group.calendar.google.com') },
      { type: 'ics', url: gcal('13e1f59521b50f503295cd8a2fad040c16a5f5e244033ef5874cdec3f2a90a0f@group.calendar.google.com') },
      { type: 'ics', url: gcal('23693dd81aaf7826cbd378dc2abe175bdc20485bdcffa16b992261f10dc8efde@group.calendar.google.com') },
      { type: 'ics', url: gcal('8f6fc3a6b1030569b801add9c6a18b34b5fd197074b977dbda567b170ce2077b@group.calendar.google.com') },
    ],
    note: 'Public skating $10 (cash only). Times change often; the rink asks you to check the day you go.',
  },
  {
    id: 'risc-north-smithfield',
    name: 'Rhode Island Sports Center',
    town: 'North Smithfield', state: 'RI', region: 'Northern RI',
    address: '1186 Eddie Dowling Hwy, North Smithfield, RI',
    website: 'https://www.risportscenter.com/',
    scheduleUrl: 'https://risc.finnlyconnect.com/schedule/179',
    sources: [{ type: 'finnly', url: 'https://risc.finnlyconnect.com/schedule/179' }],
    note: 'Full arena schedule. Mostly team ice.',
  },
  {
    id: 'providence-rink',
    name: 'The Providence Rink (outdoor, seasonal)',
    town: 'Providence', state: 'RI', region: 'Providence Area',
    address: '2 Kennedy Plaza, Providence, RI',
    website: 'https://theprovidencerink.com/',
  },
  {
    id: 'smithfield-ri',
    name: 'Smithfield Municipal Ice Rink',
    town: 'Smithfield', state: 'RI', region: 'Northern RI',
    website: 'https://www.smithfieldri.gov/departments/ice-rink',
  },
  {
    id: 'benny-magiera',
    name: 'Benny Magiera Ice Rink',
    town: 'West Warwick', state: 'RI', region: 'Kent County',
    website: 'https://westwarwickri.gov/?SEC=706EFDDE-B8A8-457B-8035-C96BC10019E1',
    note: 'Stick and puck sessions; under-18s need an adult present in the rink.',
  },

  // ================= Connecticut =================
  {
    id: 'sportscenter-shelton',
    name: 'SportsCenter of Connecticut',
    town: 'Shelton', state: 'CT', region: 'Fairfield County',
    website: 'https://www.sportscenterct.com/skate-hours/',
    scheduleUrl: 'https://scc.finnlyconnect.com/schedule/374',
    sources: [{ type: 'finnly', url: 'https://scc.finnlyconnect.com/schedule/374' }],
    note: 'Double-decker NHL rinks. Public skate, stick & puck and freestyle schedule.',
  },
  {
    id: 'stamford-twin-rinks',
    name: 'Stamford Twin Rinks',
    town: 'Stamford', state: 'CT', region: 'Fairfield County',
    website: 'https://stamfordtwinrinks.com/',
    sources: [{ type: 'daysmart', company: 'stamford' }],
  },
  {
    id: 'iscc-simsbury',
    name: 'International Skating Center of CT',
    town: 'Simsbury', state: 'CT', region: 'Hartford Area',
    website: 'https://www.isccskate.com/events/public-skate/9833',
    scheduleUrl: 'https://iscc.finnlyconnect.com/schedule/558',
    sources: [{ type: 'finnly', url: 'https://iscc.finnlyconnect.com/schedule/558' }],
    note: 'Public skate $10, rentals $5; usually Friday nights and weekends. "Stick Time" is their stick & puck.',
  },
  {
    id: 'danbury-ice',
    name: 'Danbury Ice Arena',
    town: 'Danbury', state: 'CT', region: 'Fairfield County',
    address: '1 Independence Way, Danbury, CT',
    website: 'https://danburyice.com/public-sessions/',
    note: 'Twin rinks, open seven days a week. Public skate and sticks & pucks.',
  },
  {
    id: 'enfield-twin-rinks',
    name: 'Enfield Twin Rinks',
    town: 'Enfield', state: 'CT', region: 'Hartford Area',
    address: '1 Prior Rd, Enfield, CT',
    website: 'https://www.etrinks.com/',
  },
  {
    id: 'bolton-ice-palace',
    name: 'Bolton Ice Palace',
    town: 'Bolton', state: 'CT', region: 'Hartford Area',
    address: '145 Hop River Rd, Bolton, CT',
    website: 'https://www.boltonicepalace.com/',
  },
  {
    id: 'champions-cromwell',
    name: 'Champions Skating Center',
    town: 'Cromwell', state: 'CT', region: 'Hartford Area',
    address: '6 Progress Dr, Cromwell, CT',
    website: 'https://www.championsskatingcenter.com/',
  },
  {
    id: 'newington-arena',
    name: 'Newington Arena',
    town: 'Newington', state: 'CT', region: 'Hartford Area',
    address: '300 Alumni Rd, Newington, CT',
    website: 'https://www.newingtonarena.com/',
  },

  // ================= Minnesota (Central time) =================
  {
    id: 'super-rink-blaine',
    name: 'Super Rink (National Sports Center)',
    town: 'Blaine', state: 'MN', region: 'Twin Cities North',
    website: 'https://nscsports.org/facilities/superrink/',
    scheduleUrl: 'https://nationalsportscenter.finnlyconnect.com/schedule/80',
    sources: [{ type: 'finnly', url: 'https://nationalsportscenter.finnlyconnect.com/schedule/80' }],
    note: 'Eight sheets of ice. Full schedule; public and senior skates are listed.',
  },
  {
    id: 'andover-community-center',
    name: 'Andover Community Center',
    town: 'Andover', state: 'MN', region: 'Twin Cities North',
    website: 'https://www.andovermn.gov/335/Open-Skate',
    scheduleUrl: 'https://acc.finnlyconnect.com/schedule/956',
    sources: [{ type: 'finnly', url: 'https://acc.finnlyconnect.com/schedule/956' }],
    note: 'No sticks, pucks or figure-skating jumps during open skate.',
  },
  {
    id: 'parade-minneapolis',
    name: 'Parade Ice Garden',
    town: 'Minneapolis', state: 'MN', region: 'Minneapolis & St. Paul',
    website: 'https://www.minneapolisparks.org/activities-events/winter_activities/ice_rinks/parade_ice_garden/',
    sources: [
      { type: 'finnly', url: 'https://parade.finnlyconnect.com/schedule/145' },
      { type: 'finnly', url: 'https://parade.finnlyconnect.com/schedule/146' },
    ],
    note: 'Open skating $5 ($3 seniors, under 5 free). Adult open hockey: max 20 skaters + 2 goalies; goalies call in at 8 AM that day.',
  },
  {
    id: 'maple-grove',
    name: 'Maple Grove Community Center Ice Arena',
    town: 'Maple Grove', state: 'MN', region: 'Twin Cities West & South',
    website: 'https://www.maplegrovemn.gov/274/Ice-arena',
    sources: [
      { type: 'ics', url: gcal('9b8a801985b58adc2d74b2b6fa721ee8459a0967e842fd0dd31f2b32860f3f78@group.calendar.google.com') },
      { type: 'ics', url: gcal('c6418d02ceed0913644d69da65495d46a48a967a56f6944838f5eda2ee7d3518@group.calendar.google.com') },
      { type: 'ics', url: gcal('0d85236c4d82201240ca21704e7f112a8ac9b591d183c6d1dfa1fa5a7c6eaaf7@group.calendar.google.com') },
    ],
    note: 'Open skate, adult open hockey and senior open hockey calendars.',
  },
  {
    id: 'plymouth-ice-center',
    name: 'Plymouth Ice Center',
    town: 'Plymouth', state: 'MN', region: 'Twin Cities West & South',
    phone: '763-509-5250',
    website: 'https://www.plymouthmn.gov/departments/parks-recreation/ice-center/open-skate-open-hockey',
    note: 'Open skating year-round, plus open hockey.',
  },
  {
    id: 'braemar-edina',
    name: 'Braemar Arena',
    town: 'Edina', state: 'MN', region: 'Twin Cities West & South',
    website: 'https://www.edinamn.gov/492/Open-Skating',
    note: 'Open skating and open hockey; register through the city site.',
  },
  {
    id: 'hopkins-pavilion',
    name: 'Hopkins Pavilion',
    town: 'Hopkins', state: 'MN', region: 'Twin Cities West & South',
    website: 'https://www.hopkinsmn.com/192/Open-Skate',
  },
  {
    id: 'ramsey-county-arenas',
    name: 'Ramsey County arenas',
    town: 'Ramsey County', state: 'MN', region: 'Minneapolis & St. Paul',
    website: 'https://www.ramseycountymn.gov/residents/parks-recreation/ice-arenas-fieldhouse/skating-programs/open-skate',
    note: 'Free open skating at several county arenas; dates are on the county calendar (search "Open Skate").',
  },

  // ================= Florida =================
  {
    id: 'boca-ice',
    name: 'Boca Ice',
    town: 'Boca Raton', state: 'FL', region: 'South Florida',
    website: 'https://www.bocaice.com/public-skating/',
    sources: [{ type: 'daysmart', company: 'bocaice', resourceIds: [1, 7] }],
    note: '"Figure Ice" is their freestyle; "Open Hockey 17+" is pickup.',
  },
  {
    id: 'baptist-health-iceplex',
    name: 'Baptist Health IcePlex',
    town: 'Fort Lauderdale', state: 'FL', region: 'South Florida',
    website: 'https://www.ftlwarmemorial.com/public-skating',
    sources: [{ type: 'daysmart', company: 'warmemorial', resourceIds: [1, 6] }],
    note: 'Florida Panthers practice rink at War Memorial. Create a DaySmart account before skating.',
  },
  {
    id: 'space-coast-iceplex',
    name: 'Space Coast Iceplex',
    town: 'Rockledge', state: 'FL', region: 'Central Florida',
    address: '720 Roy Wall Blvd, Rockledge, FL', phone: '321-504-7500',
    website: 'https://www.spacecoasticeplex.com/public-skating/',
    sources: [{ type: 'daysmart', company: 'spacecoast', resourceIds: [1] }],
  },
  {
    id: 'tbsa-oldsmar',
    name: 'Tampa Bay Skating Academy (Oldsmar)',
    town: 'Oldsmar', state: 'FL', region: 'Tampa Bay',
    website: 'https://tampabayice.com/',
    sources: [{ type: 'daysmart', company: 'tampabayice', resourceIds: [1, 4] }],
  },
  {
    id: 'clearwater-ice-arena',
    name: 'Clearwater Ice Arena',
    town: 'Clearwater', state: 'FL', region: 'Tampa Bay',
    phone: '727-536-5843',
    website: 'https://tampabayice.com/',
    sources: [{ type: 'daysmart', company: 'tampabayice', resourceIds: [6, 7] }],
  },
  {
    id: 'tbsa-countryside',
    name: 'Tampa Bay Skating Academy (Countryside Mall)',
    town: 'Clearwater', state: 'FL', region: 'Tampa Bay',
    website: 'https://tampabayice.com/',
    sources: [{ type: 'daysmart', company: 'tampabayice', resourceIds: [30] }],
  },
  {
    id: 'ellenton-ice',
    name: 'Ellenton Ice and Sports Complex',
    town: 'Ellenton', state: 'FL', region: 'Tampa Bay',
    address: '5309 29th St E, Ellenton, FL', phone: '941-723-3663',
    website: 'https://www.ellentonice.com/public-skating/',
    sources: [{ type: 'daysmart', company: 'ellenton', resourceIds: [1, 6] }],
    note: '"Public Session" is their public skate.',
  },
  {
    id: 'panthers-iceden',
    name: 'Panthers IceDen',
    town: 'Coral Springs', state: 'FL', region: 'South Florida',
    website: 'https://www.panthersiceden.com/public-skating/public-skating-drop-in-calendar',
    note: 'Public skating usually Friday night, Saturday afternoon and night, and Sunday afternoon. Create an account online before skating.',
  },
  {
    id: 'orlando-ice-den',
    name: 'RDV Ice Den',
    town: 'Maitland', state: 'FL', region: 'Central Florida',
    phone: '407-916-2550',
    website: 'https://www.orlandoiceden.com/public-skating',
    note: 'Public skating seven days a week; teen night with a DJ on Fridays.',
  },
  {
    id: 'adventhealth-center-ice',
    name: 'AdventHealth Center Ice',
    town: 'Wesley Chapel', state: 'FL', region: 'Tampa Bay',
    website: 'https://ahcenterice.com/publicskate/',
  },
  {
    id: 'community-first-igloo',
    name: 'Community First Igloo',
    town: 'Jacksonville', state: 'FL', region: 'North Florida',
    address: '3605 Philips Hwy, Jacksonville, FL',
    website: 'https://communityfirstigloo.com/skating/public-skating/',
    note: 'Public skating, drop-in hockey and stick & puck.',
  },
  {
    id: 'hertz-arena-rinks',
    name: 'Hertz Arena Recreational Rinks',
    town: 'Estero', state: 'FL', region: 'Southwest Florida',
    website: 'https://hertzarena.com/arena-information/recreational-arena/',
  },

  // ================= Colorado (Mountain time) =================
  {
    id: 'sertich-colorado-springs',
    name: 'Sertich Ice Center',
    town: 'Colorado Springs', state: 'CO', region: 'Colorado Springs',
    website: 'https://coloradosprings.gov/sertich-ice-center/page/public-skating',
    scheduleUrl: 'https://sertich.finnlyconnect.com/schedule/850',
    sources: [{ type: 'finnly', url: 'https://sertich.finnlyconnect.com/schedule/850' }],
    note: 'City-run. Public skate, freestyle, and adult and 60+ drop-in hockey.',
  },
  {
    id: 'family-sports-centennial',
    name: 'Family Sports Ice Arena',
    town: 'Centennial', state: 'CO', region: 'Denver Metro',
    website: 'https://www.ssprd.org/family-sports-ice-arena',
    scheduleUrl: 'https://ssprd.finnlyconnect.com/schedule/246',
    sources: [{ type: 'finnly', url: 'https://ssprd.finnlyconnect.com/schedule/246' }],
    note: 'South Suburban Parks & Rec; Colorado Avalanche training rink. "Silver Skates" is a 30+ public skate.',
  },
  {
    id: 'sssc-highlands-ranch',
    name: 'South Suburban Sports Complex',
    town: 'Highlands Ranch', state: 'CO', region: 'Denver Metro',
    address: '4810 E County Line Rd, Highlands Ranch, CO', phone: '303-798-7515',
    website: 'https://www.ssprd.org/sports-complex',
    scheduleUrl: 'https://ssprd.finnlyconnect.com/schedule/247',
    sources: [{ type: 'finnly', url: 'https://ssprd.finnlyconnect.com/schedule/247' }],
    note: 'Three rinks. "Silver Skates" is a 30+ public skate.',
  },
  {
    id: 'du-ritchie-center',
    name: 'University of Denver (Ritchie Center)',
    town: 'Denver', state: 'CO', region: 'Denver Metro',
    website: 'https://ritchiecenter.du.edu/',
    sources: [
      { type: 'ics', url: gcal('qtst6uerc2tamp5pbn2p4n4dko@group.calendar.google.com') },
      { type: 'ics', url: gcal('pc78u2neckrn16pj4v92r6mufg@group.calendar.google.com') },
      { type: 'ics', url: gcal('4u0hkl9u6ii0o39uk1v90nnv6o@group.calendar.google.com') },
    ],
    note: 'Public skate, stick & puck and drop-in hockey (18+). Reserve each session online and print a parking permit.',
  },
  {
    id: 'ice-ranch-littleton',
    name: 'The Ice Ranch',
    town: 'Littleton', state: 'CO', region: 'Denver Metro',
    website: 'https://www.theiceranch.com/',
    sources: [{ type: 'daysmart', company: 'iceranch', resourceIds: [1, 6] }],
    note: 'Full arena schedule; mostly team ice.',
  },
  {
    id: 'edge-littleton',
    name: 'Edge Ice Arena',
    town: 'Littleton', state: 'CO', region: 'Denver Metro',
    address: '6623 S Ward St, Littleton, CO', phone: '303-409-2222',
    website: 'https://www.ifoothills.org/edge-ice-arena/',
  },
  {
    id: 'ice-centre-westminster',
    name: 'Ice Centre at the Promenade',
    town: 'Westminster', state: 'CO', region: 'Denver Metro',
    website: 'https://icecentre.com/schedules/public-skating-schedule/',
  },
  {
    id: 'big-bear-denver',
    name: 'Big Bear Ice Arena',
    town: 'Denver', state: 'CO', region: 'Denver Metro',
    website: 'https://www.bigbearice.com/',
    note: 'Stick & puck and public skate are booked through their EZFacility page.',
  },
  {
    id: 'broadmoor-world-arena',
    name: 'Broadmoor World Arena Ice Hall',
    town: 'Colorado Springs', state: 'CO', region: 'Colorado Springs',
    website: 'https://www.broadmoorworldarena.com/icehall/publicactivities',
  },
  {
    id: 'dobson-vail',
    name: 'Dobson Ice Arena',
    town: 'Vail', state: 'CO', region: 'Mountains',
    phone: '970-479-2271',
    website: 'https://www.vailrec.com/public-skating-hockey',
    note: 'Open skating needs no registration.',
  },

  // ================= Michigan =================
  {
    id: 'birmingham-ice',
    name: 'Birmingham Ice Sports Arena',
    town: 'Birmingham', state: 'MI', region: 'Metro Detroit',
    website: 'https://www.bhamgov.org/about_birmingham/city_departments/public_services/parks___recreation/parks___facilities/ice_sports_arena.php',
    sources: [{ type: 'daysmart', company: 'birmingham', resourceIds: [5, 14] }],
    note: 'City-run. Morning, afternoon and adult open skates on weekdays.',
  },
  {
    id: 'kennedy-trenton',
    name: 'Kennedy Recreation Center',
    town: 'Trenton', state: 'MI', region: 'Metro Detroit',
    website: 'https://www.trentonmi.org/',
    sources: [{ type: 'daysmart', company: 'trenton', resourceIds: [1, 2, 3] }],
    note: 'Three rinks. Open skate, adult and senior drop-in hockey.',
  },
  {
    id: 'detroit-skating-club',
    name: 'Detroit Skating Club',
    town: 'Bloomfield Hills', state: 'MI', region: 'Metro Detroit',
    website: 'https://www.detroitskatingclub.org/',
    sources: [{ type: 'daysmart', company: 'detroitskating', resourceIds: [1, 7, 8] }],
    note: 'Figure skating club; mostly member and club ice, with some public skating.',
  },
  {
    id: 'arctic-edge-canton',
    name: 'Arctic Edge Ice Arena',
    town: 'Canton', state: 'MI', region: 'Metro Detroit',
    address: '46615 Michigan Ave, Canton, MI',
    website: 'https://www.arcticarenas.com/page/show/3517362-open-skate',
  },
  {
    id: 'farmington-hills-ice',
    name: 'Farmington Hills Ice Arena',
    town: 'Farmington Hills', state: 'MI', region: 'Metro Detroit',
    address: '35500 W 8 Mile Rd, Farmington Hills, MI', phone: '248-473-1810',
    website: 'https://www.fhgov.com/ice/',
  },
  {
    id: 'royal-oak-ice',
    name: 'Royal Oak Ice Arena',
    town: 'Royal Oak', state: 'MI', region: 'Metro Detroit',
    website: 'https://www.royaloakicearena.com/public-skating',
  },
  {
    id: 'ice-cube-ann-arbor',
    name: 'Biggby Coffee Ice Cube (Ann Arbor)',
    town: 'Ann Arbor', state: 'MI', region: 'Ann Arbor & Lansing',
    website: 'https://www.biggbycoffeeicecube.com/ann-arbor/public-skate',
  },
  {
    id: 'ice-cube-east-lansing',
    name: 'Biggby Coffee Ice Cube (East Lansing)',
    town: 'East Lansing', state: 'MI', region: 'Ann Arbor & Lansing',
    website: 'https://www.biggbycoffeeicecube.com/east-lansing/public-skating',
  },
  {
    id: 'yost-ann-arbor',
    name: 'Yost Ice Arena (University of Michigan)',
    town: 'Ann Arbor', state: 'MI', region: 'Ann Arbor & Lansing',
    website: 'https://yost.umich.edu/',
    note: 'Public skate several times a week, around the hockey schedule.',
  },
  {
    id: 'patterson-grand-rapids',
    name: 'Patterson Ice Center',
    town: 'Grand Rapids', state: 'MI', region: 'West Michigan',
    website: 'https://www.pattersonicecenter.com/',
  },

  // ================= New York =================
  {
    id: 'northwell-east-meadow',
    name: 'Northwell Health Ice Center',
    town: 'East Meadow', state: 'NY', region: 'Long Island',
    website: 'https://www.northwellhealthicecenter.com/',
    sources: [{ type: 'daysmart', company: 'islanders', resourceIds: [1, 6] }],
    note: 'New York Islanders practice facility.',
  },
  {
    id: 'islanders-iceworks',
    name: 'Islanders Iceworks',
    town: 'Syosset', state: 'NY', region: 'Long Island',
    website: 'https://www.northwellhealthicecenter.com/',
    sources: [{ type: 'daysmart', company: 'islanders', resourceIds: [16, 17] }],
  },
  {
    id: 'world-ice-queens',
    name: 'World Ice Arena',
    town: 'Queens', state: 'NY', region: 'New York City',
    website: 'https://www.worldice.com/',
    sources: [{ type: 'daysmart', company: 'worldice', resourceIds: [1], exclude: /goalies/i }],
    note: "Stick n' puck and open hockey are listed with skater spots; goalie spots are sold separately.",
  },
  {
    id: 'nexus-utica',
    name: 'Nexus Center',
    town: 'Utica', state: 'NY', region: 'Upstate',
    website: 'https://www.nexuscenter.com/',
    sources: [{ type: 'daysmart', company: 'utica', resourceIds: [1, 8, 9] }],
    note: 'Full schedule for the three Nexus Center rinks; mostly team ice.',
  },
  {
    id: 'kiwanis-saugerties',
    name: 'Kiwanis Ice Arena',
    town: 'Saugerties', state: 'NY', region: 'Hudson Valley',
    address: '6 Small World Ave, Saugerties, NY', phone: '845-247-2590',
    website: 'https://www.kiwanisicearena.com/public-sessions',
    note: 'Public skating, cosmic skate, stick & puck, drop-in hockey and freestyle.',
  },
  {
    id: 'long-beach-ice',
    name: 'City of Long Beach Ice Arena',
    town: 'Long Beach', state: 'NY', region: 'Long Island',
    website: 'https://www.longbeachny.gov/icearena',
  },
  {
    id: 'rochester-ice-center',
    name: 'Rochester Ice Center',
    town: 'Fairport', state: 'NY', region: 'Upstate',
    address: '80 Lyndon Rd, Fairport, NY',
    website: 'https://www.rochestericecenter.com/',
  },
  {
    id: 'albany-county-hockey',
    name: 'Albany County Hockey Facility',
    town: 'Albany', state: 'NY', region: 'Upstate',
    website: 'https://albanycounty.recdesk.com/Community/Facility/Detail?facilityId=47',
    note: 'Public skate $4 (seniors $3, under 5 $2); skate rental $3.',
  },
  {
    id: 'nyc-parks-rinks',
    name: 'NYC Parks rinks (Wollman and others)',
    town: 'New York City', state: 'NY', region: 'New York City',
    website: 'https://www.nycgovparks.org/facilities/iceskating',
    note: 'Seasonal outdoor rinks, roughly late October to March.',
  },

  // ================= Vermont =================
  {
    id: 'cairns-south-burlington',
    name: 'Cairns Arena',
    town: 'South Burlington', state: 'VT', region: 'Burlington Area',
    website: 'https://www.cairnsarena.com/',
    scheduleUrl: 'https://cairnsarena.finnlyconnect.com/schedule/460',
    sources: [{ type: 'finnly', url: 'https://cairnsarena.finnlyconnect.com/schedule/460' }],
    note: 'Full schedule for both rinks.',
  },
  {
    id: 'cvmcc-montpelier',
    name: 'Central Vermont Memorial Civic Center',
    town: 'Montpelier', state: 'VT', region: 'Central',
    address: '10 Gallison Hill Rd, Montpelier, VT', phone: '802-229-5900',
    website: 'https://www.cvmcc.org/rink-schedule',
    sources: [{ type: 'ics', url: gcal('cvmcc.org_o8dgq6m6e2dsovopns8hkfki14@group.calendar.google.com') }],
    note: 'Full rink calendar. Public skating $5, rentals $5.',
  },
  {
    id: 'msc-middlebury',
    name: 'Memorial Sports Center',
    town: 'Middlebury', state: 'VT', region: 'Champlain Valley',
    address: '296 Buttolph Dr, Middlebury, VT',
    website: 'https://memorialsportscenter.org/activities/public-skating/',
    sources: [{ type: 'ics', url: gcal('c_038c123c528eaac1dfb02c3f7001344b6387b876594bcd55d18a7122e95d8e64@group.calendar.google.com') }],
    note: 'Public skating & stick and puck calendar. Sessions are posted as the season starts.',
  },
  {
    id: 'leddy-burlington',
    name: 'Leddy Park Arena',
    town: 'Burlington', state: 'VT', region: 'Burlington Area',
    address: '216 Leddy Park Rd, Burlington, VT', phone: '802-864-0123',
    website: 'https://www.burlingtonvt.gov/1092/Ice-Skating',
    note: 'The public skate schedule is released monthly on the City of Burlington calendar.',
  },
  {
    id: 'essex-skating',
    name: 'Essex Skating Facility',
    town: 'Essex Junction', state: 'VT', region: 'Burlington Area',
    address: '2 Educational Dr, Essex Junction, VT', phone: '802-857-7300',
    website: 'https://www.ewsd.org/page/skating-facility',
    note: 'Public skating and stick & puck, September to May; times are on the school district events calendar.',
  },
  {
    id: 'withington-brattleboro',
    name: 'Nelson Withington Skating Facility',
    town: 'Brattleboro', state: 'VT', region: 'Southern',
    address: '61 Guilford St, Brattleboro, VT',
    website: 'https://brattleboro.gov/skating-facility',
  },
  {
    id: 'stowe-arena',
    name: 'Stowe Arena',
    town: 'Stowe', state: 'VT', region: 'Central',
    address: '350 Park St, Stowe, VT',
    website: 'https://www.stowerec.org/',
  },
  {
    id: 'fenton-chester-arena',
    name: 'Fenton Chester Arena',
    town: 'Lyndonville', state: 'VT', region: 'Northeast Kingdom',
    website: 'https://www.chesterarena.org/',
  },

  // ================= Ontario =================
  {
    id: 'toronto-agincourt',
    name: 'Agincourt Community Recreation Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto East (Scarborough)',
    address: '31 Glen Watford Dr, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=523',
    sources: toronto(523),
  },
  {
    id: 'toronto-albion-arena',
    name: 'Albion Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto West (Etobicoke York)',
    address: '1501 Albion Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=800',
    sources: toronto(800),
  },
  {
    id: 'toronto-amesbury-sports-complex',
    name: 'Amesbury Sports Complex',
    town: 'Toronto', state: 'ON', region: 'Toronto West (Etobicoke York)',
    address: '155 Culford Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=480',
    sources: toronto(480),
  },
  {
    id: 'toronto-angela-james-arena-tennis-courts',
    name: 'Angela James Arena & Tennis Courts',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '165 Grenoble Dr, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=582',
    sources: toronto(582),
  },
  {
    id: 'toronto-baycrest-arena',
    name: 'Baycrest Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '160 Neptune Dr, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=512',
    sources: toronto(512),
  },
  {
    id: 'toronto-bayview-arena',
    name: 'Bayview Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '3230 Bayview Ave, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=515',
    sources: toronto(515),
  },
  {
    id: 'toronto-centennial-park-arena-etobicoke',
    name: 'Centennial Park Arena - Etobicoke',
    town: 'Toronto', state: 'ON', region: 'Toronto West (Etobicoke York)',
    address: '156 Centennial Park Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=913',
    sources: toronto(913),
  },
  {
    id: 'toronto-centennial-recreation-centre-scarborough',
    name: 'Centennial Recreation Centre - Scarborough',
    town: 'Toronto', state: 'ON', region: 'Toronto East (Scarborough)',
    address: '1967 Ellesmere Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=537',
    sources: toronto(537),
  },
  {
    id: 'toronto-central-arena',
    name: 'Central Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto West (Etobicoke York)',
    address: '50 Montgomery Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=824',
    sources: toronto(824),
  },
  {
    id: 'toronto-chris-tonks-arena',
    name: 'Chris Tonks Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto West (Etobicoke York)',
    address: '95 Black Creek Dr, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=476',
    sources: toronto(476),
  },
  {
    id: 'toronto-commander',
    name: 'Commander Recreation Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto East (Scarborough)',
    address: '140 Commander Blvd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=558',
    sources: toronto(558),
  },
  {
    id: 'toronto-cummer-park',
    name: 'Cummer Park Community Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '6000 Leslie St, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=499',
    sources: toronto(499),
  },
  {
    id: 'toronto-don-mills-civitan-arena',
    name: 'Don Mills Civitan Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '1030 Don Mills Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=548',
    sources: toronto(548),
  },
  {
    id: 'toronto-don-montgomery',
    name: 'Don Montgomery Community Recreation Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto East (Scarborough)',
    address: '2467 Eglinton Ave E, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=712',
    sources: toronto(712),
  },
  {
    id: 'toronto-downsview-arena',
    name: 'Downsview Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto West (Etobicoke York)',
    address: '1633 Wilson Ave, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=568',
    sources: toronto(568),
  },
  {
    id: 'toronto-east-york-memorial-arena',
    name: 'East York Memorial Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto Central & East York',
    address: '888 Cosburn Ave, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=330',
    sources: toronto(330),
  },
  {
    id: 'toronto-fenside-arena',
    name: 'Fenside Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '30 Slidell Cres, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=303',
    sources: toronto(303),
  },
  {
    id: 'toronto-gord-and-irene-risk',
    name: 'Gord and Irene Risk Community Recreation Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto West (Etobicoke York)',
    address: '2650 Finch Ave W, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=642',
    sources: toronto(642),
  },
  {
    id: 'toronto-goulding',
    name: 'Goulding Community Recreation Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '45 Goulding Ave, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=643',
    sources: toronto(643),
  },
  {
    id: 'toronto-grandravine',
    name: 'Grandravine Community Recreation Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '23 Grandravine Dr, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=647',
    sources: toronto(647),
  },
  {
    id: 'toronto-habitant-arena',
    name: 'Habitant Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto West (Etobicoke York)',
    address: '3383 Weston Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=652',
    sources: toronto(652),
  },
  {
    id: 'toronto-herbert-h-carnegie-centennial',
    name: 'Herbert H. Carnegie Centennial Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '580 Finch Ave W, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=483',
    sources: toronto(483),
  },
  {
    id: 'toronto-heron-park',
    name: 'Heron Park Community Recreation Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto East (Scarborough)',
    address: '292 Manse Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=633',
    sources: toronto(633),
  },
  {
    id: 'toronto-john-booth-memorial-arena',
    name: 'John Booth Memorial Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto West (Etobicoke York)',
    address: '230 Gosford Blvd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=667',
    sources: toronto(667),
  },
  {
    id: 'toronto-lambton-arena',
    name: 'Lambton Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto Central & East York',
    address: '4100 Dundas St W, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=479',
    sources: toronto(479),
  },
  {
    id: 'toronto-long-branch-arena',
    name: 'Long Branch Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto West (Etobicoke York)',
    address: '75 Arcadian Cir, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=803',
    sources: toronto(803),
  },
  {
    id: 'toronto-malvern',
    name: 'Malvern Recreation Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto East (Scarborough)',
    address: '30 Sewells Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=702',
    sources: toronto(702),
  },
  {
    id: 'toronto-mcgregor-park',
    name: 'McGregor Park Community Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto East (Scarborough)',
    address: '2231 Lawrence Ave. E, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=506',
    sources: toronto(506),
  },
  {
    id: 'toronto-mimico-arena',
    name: 'Mimico Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto West (Etobicoke York)',
    address: '31 Drummond St, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=802',
    sources: toronto(802),
  },
  {
    id: 'toronto-mitchell-field',
    name: 'Mitchell Field Community Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '89 Church Ave, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=693',
    sources: toronto(693),
  },
  {
    id: 'toronto-oriole',
    name: 'Oriole Community Recreation Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '2975 Don Mills Rd. W, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=714',
    sources: toronto(714),
  },
  {
    id: 'toronto-park-lawn-park',
    name: 'Park Lawn Park',
    town: 'Toronto', state: 'ON', region: 'Toronto West (Etobicoke York)',
    address: '330 Park Lawn Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=858',
    sources: toronto(858),
    note: 'Outdoor rink; City of Toronto drop-in skating.',
  },
  {
    id: 'toronto-phil-white-arena',
    name: 'Phil White Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto Central & East York',
    address: '443 Arlington Ave, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=477',
    sources: toronto(477),
  },
  {
    id: 'toronto-pine-point-arena',
    name: 'Pine Point Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto West (Etobicoke York)',
    address: '15 Grierson Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=801',
    sources: toronto(801),
  },
  {
    id: 'toronto-pleasantview',
    name: 'Pleasantview Community Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '545 Van Horne Ave, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=732',
    sources: toronto(732),
  },
  {
    id: 'toronto-roding',
    name: 'Roding Community Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '600 Roding St, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=744',
    sources: toronto(744),
  },
  {
    id: 'toronto-scarborough-arena-gardens',
    name: 'Scarborough Arena Gardens',
    town: 'Toronto', state: 'ON', region: 'Toronto East (Scarborough)',
    address: '75 Birchmount Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=3493',
    sources: toronto(3493),
  },
  {
    id: 'toronto-scarborough-village',
    name: 'Scarborough Village Recreation Centre',
    town: 'Toronto', state: 'ON', region: 'Toronto East (Scarborough)',
    address: '3600 Kingston Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=743',
    sources: toronto(743),
  },
  {
    id: 'toronto-victoria-village-recreation-centre-and-arena',
    name: 'Victoria Village Recreation Centre and Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '190 Bermondsey Rd, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=771',
    sources: toronto(771),
  },
  {
    id: 'toronto-york-mills-arena',
    name: 'York Mills Arena',
    town: 'Toronto', state: 'ON', region: 'Toronto North (North York)',
    address: '2539 Bayview Ave, Toronto, ON',
    website: 'https://www.toronto.ca/explore-enjoy/parks-recreation/places-spaces/parks-and-recreation-facilities/location/?id=778',
    sources: toronto(778),
  },
  {
    id: 'canlan-etobicoke',
    name: 'Canlan CWENCH Centre',
    town: 'Toronto (Etobicoke)', state: 'ON', region: 'Toronto West (Etobicoke York)',
    website: 'https://www.canlansports.com/',
    sources: [{ type: 'daysmart', company: 'canlan', resourceIds: [207, 208, 209, 210], exclude: /goalies/i }],
    note: 'Canlan Sports. Public skating and stick & puck; book online.',
  },
  {
    id: 'canlan-york',
    name: 'Canlan NFP Athletic Centre (York)',
    town: 'Toronto (North York)', state: 'ON', region: 'Toronto North (North York)',
    website: 'https://www.canlansports.com/',
    sources: [{ type: 'daysmart', company: 'canlan', resourceIds: [3, 4, 5, 6, 7, 8], exclude: /goalies/i }],
    note: 'Canlan Sports, six rinks. Public skate and stick & puck.',
  },
  {
    id: 'canlan-oakville',
    name: 'Canlan Entripy Centre',
    town: 'Oakville', state: 'ON', region: 'Greater Toronto Area',
    website: 'https://www.canlansports.com/',
    sources: [{ type: 'daysmart', company: 'canlan', resourceIds: [102, 103, 104, 105], exclude: /goalies/i }],
    note: 'Canlan Sports. Stick & puck and shinny.',
  },
  {
    id: 'canlan-oshawa',
    name: 'Canlan Oshawa',
    town: 'Oshawa', state: 'ON', region: 'Greater Toronto Area',
    website: 'https://www.canlansports.com/',
    sources: [{ type: 'daysmart', company: 'canlan', resourceIds: [54, 65], exclude: /goalies/i }],
    note: 'Canlan Sports. Stick & puck and shinny.',
  },
  {
    id: 'ottawa-city-arenas',
    name: 'City of Ottawa arenas',
    town: 'Ottawa', state: 'ON', region: 'Ottawa',
    website: 'https://ottawa.ca/en/recreation-and-parks/drop-activities/descriptions-safety-locations/skating-and-ice-sports/drop-skating-locations',
    note: 'Public, family, adult and 50+ skates at about ten city arenas; drop-in schedules are on ottawa.ca.',
  },

  // ================= Québec =================
  {
    id: 'montreal-ahuntsic',
    name: 'Aréna Ahuntsic',
    town: 'Montréal (Ahuntsic-Cartierville)', state: 'QC', region: 'Montréal',
    address: '10560, rue Saint-Hubert, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-ahuntsic',
    sources: montreal('arena-ahuntsic'),
  },
  {
    id: 'montreal-andre-laperriere',
    name: 'Aréna André-Laperrière',
    town: 'Montréal (Outremont)', state: 'QC', region: 'Montréal',
    address: '999, avenue McEachran, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-andre-laperriere',
    sources: montreal('arena-andre-laperriere'),
  },
  {
    id: 'montreal-bill-durnan',
    name: 'Aréna Bill-Durnan',
    town: 'Montréal (Côte-des-Neiges–Notre-Dame-de-Grâce)', state: 'QC', region: 'Montréal',
    address: '4988, rue Vézina, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-bill-durnan',
    sources: montreal('arena-bill-durnan'),
  },
  {
    id: 'montreal-camillien-houde',
    name: 'Aréna Camillien-Houde',
    town: 'Montréal (Ville-Marie)', state: 'QC', region: 'Montréal',
    address: '1696, rue Montcalm, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-camillien-houde',
    sources: montreal('arena-camillien-houde'),
  },
  {
    id: 'montreal-chaumont',
    name: 'Aréna Chaumont',
    town: 'Montréal (Anjou)', state: 'QC', region: 'Montréal',
    address: '8750, avenue Chaumont, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-chaumont',
    sources: montreal('arena-chaumont'),
  },
  {
    id: 'montreal-chenier',
    name: 'Aréna Chénier',
    town: 'Montréal (Anjou)', state: 'QC', region: 'Montréal',
    address: '8200, avenue Chénier, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-chenier',
    sources: montreal('arena-chenier'),
  },
  {
    id: 'montreal-clement-jette',
    name: 'Aréna Clément-Jetté',
    town: 'Montréal (Mercier–Hochelaga-Maisonneuve)', state: 'QC', region: 'Montréal',
    address: '8780, avenue Dubuisson, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-clement-jette',
    sources: montreal('arena-clement-jette'),
  },
  {
    id: 'montreal-de-saint-michel',
    name: 'Aréna de Saint-Michel',
    town: 'Montréal (Villeray–Saint-Michel–Parc-Extension)', state: 'QC', region: 'Montréal',
    address: '3440, rue Jarry Est, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-de-saint-michel',
    sources: montreal('arena-de-saint-michel'),
  },
  {
    id: 'montreal-des-patineuses',
    name: 'Aréna des Patineuses',
    town: 'Montréal (Le Plateau-Mont-Royal)', state: 'QC', region: 'Montréal',
    address: '5633, rue Saint-Dominique, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-des-patineuses',
    sources: montreal('arena-des-patineuses'),
  },
  {
    id: 'montreal-doug-harvey',
    name: 'Aréna Doug-Harvey',
    town: 'Montréal (Côte-des-Neiges–Notre-Dame-de-Grâce)', state: 'QC', region: 'Montréal',
    address: '4985, avenue West Hill, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-doug-harvey',
    sources: montreal('arena-doug-harvey'),
  },
  {
    id: 'montreal-du-complexe-st-jean-vianney',
    name: 'Aréna du complexe St-Jean-Vianney',
    town: 'Montréal (Rivière-des-Prairies–Pointe-aux-Trembles)', state: 'QC', region: 'Montréal',
    address: '12640, boulevard Gouin Est, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-du-complexe-st-jean-vianney',
    sources: montreal('arena-du-complexe-st-jean-vianney'),
  },
  {
    id: 'montreal-etienne-desmarteau',
    name: 'Aréna Étienne-Desmarteau',
    town: 'Montréal (Rosemont–La Petite-Patrie)', state: 'QC', region: 'Montréal',
    address: '3430, rue de Bellechasse, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-etienne-desmarteau',
    sources: montreal('arena-etienne-desmarteau'),
  },
  {
    id: 'montreal-fleury',
    name: 'Aréna Fleury',
    town: 'Montréal (Montréal-Nord)', state: 'QC', region: 'Montréal',
    address: '3700, rue Fleury Est, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-fleury',
    sources: montreal('arena-fleury'),
  },
  {
    id: 'montreal-francis-bouillon',
    name: 'Aréna Francis-Bouillon',
    town: 'Montréal (Mercier–Hochelaga-Maisonneuve)', state: 'QC', region: 'Montréal',
    address: '3175, rue de Rouen, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-francis-bouillon',
    sources: montreal('arena-francis-bouillon'),
  },
  {
    id: 'montreal-garon',
    name: 'Aréna Garon',
    town: 'Montréal (Montréal-Nord)', state: 'QC', region: 'Montréal',
    address: '11212, avenue Garon, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-garon',
    sources: montreal('arena-garon'),
  },
  {
    id: 'montreal-georges-mantha',
    name: 'Aréna Georges-Mantha',
    town: 'Montréal (Le Sud-Ouest)', state: 'QC', region: 'Montréal',
    address: '5485, chemin de la Côte-Saint-Paul, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-georges-mantha',
    sources: montreal('arena-georges-mantha'),
  },
  {
    id: 'montreal-howie-morenz',
    name: 'Aréna Howie-Morenz',
    town: 'Montréal (Villeray–Saint-Michel–Parc-Extension)', state: 'QC', region: 'Montréal',
    address: '8650, avenue Querbes, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-howie-morenz',
    sources: montreal('arena-howie-morenz'),
  },
  {
    id: 'montreal-jacques-lemaire',
    name: 'Aréna Jacques-Lemaire',
    town: 'Montréal (LaSalle)', state: 'QC', region: 'Montréal',
    address: '8681, boulevard Champlain, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-jacques-lemaire',
    sources: montreal('arena-jacques-lemaire'),
  },
  {
    id: 'montreal-marcelin-wilson',
    name: 'Aréna Marcelin-Wilson',
    town: 'Montréal (Ahuntsic-Cartierville)', state: 'QC', region: 'Montréal',
    address: '11301, boulevard de l\'Acadie, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-marcelin-wilson',
    sources: montreal('arena-marcelin-wilson'),
  },
  {
    id: 'montreal-martin-brodeur',
    name: 'Aréna Martin-Brodeur',
    town: 'Montréal (Saint-Léonard)', state: 'QC', region: 'Montréal',
    address: '5300, boulevard Robert, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-martin-brodeur',
    sources: montreal('arena-martin-brodeur'),
  },
  {
    id: 'montreal-martin-lapointe',
    name: 'Aréna Martin-Lapointe',
    town: 'Montréal (Lachine)', state: 'QC', region: 'Montréal',
    address: '183, rue des Érables, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-martin-lapointe',
    sources: montreal('arena-martin-lapointe'),
  },
  {
    id: 'montreal-maurice-richard',
    name: 'Aréna Maurice-Richard',
    town: 'Montréal (Mercier–Hochelaga-Maisonneuve)', state: 'QC', region: 'Montréal',
    address: '2800, rue Viau, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-maurice-richard',
    sources: montreal('arena-maurice-richard'),
  },
  {
    id: 'montreal-michel-normandin',
    name: 'Aréna Michel-Normandin',
    town: 'Montréal (Ahuntsic-Cartierville)', state: 'QC', region: 'Montréal',
    address: '850, avenue Émile-Journault, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-michel-normandin',
    sources: montreal('arena-michel-normandin'),
  },
  {
    id: 'montreal-mont-royal',
    name: 'Aréna Mont-Royal',
    town: 'Montréal (Le Plateau-Mont-Royal)', state: 'QC', region: 'Montréal',
    address: '4365, rue Cartier, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-mont-royal',
    sources: montreal('arena-mont-royal'),
  },
  {
    id: 'montreal-pere-marquette',
    name: 'Aréna Père-Marquette',
    town: 'Montréal (Rosemont–La Petite-Patrie)', state: 'QC', region: 'Montréal',
    address: '1600, rue De Drucourt, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-pere-marquette',
    sources: montreal('arena-pere-marquette'),
  },
  {
    id: 'montreal-pierre-pete-morin',
    name: 'Aréna Pierre « Pete » Morin',
    town: 'Montréal (Lachine)', state: 'QC', region: 'Montréal',
    address: '1925, rue Saint-Antoine, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-pierre-pete-morin',
    sources: montreal('arena-pierre-pete-morin'),
  },
  {
    id: 'montreal-raymond-bourque',
    name: 'Aréna Raymond-Bourque',
    town: 'Montréal (Saint-Laurent)', state: 'QC', region: 'Montréal',
    address: '2345, boulevard Thimens, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-raymond-bourque',
    sources: montreal('arena-raymond-bourque'),
  },
  {
    id: 'montreal-rene-masson',
    name: 'Aréna René-Masson',
    town: 'Montréal (Rivière-des-Prairies–Pointe-aux-Trembles)', state: 'QC', region: 'Montréal',
    address: '9175, boulevard Perras, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-rene-masson',
    sources: montreal('arena-rene-masson'),
  },
  {
    id: 'montreal-roberto-luongo',
    name: 'Aréna Roberto-Luongo',
    town: 'Montréal (Saint-Léonard)', state: 'QC', region: 'Montréal',
    address: '7755, rue Colbert, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-roberto-luongo',
    sources: montreal('arena-roberto-luongo'),
  },
  {
    id: 'montreal-rodrigue-gilbert',
    name: 'Aréna Rodrigue-Gilbert',
    town: 'Montréal (Rivière-des-Prairies–Pointe-aux-Trembles)', state: 'QC', region: 'Montréal',
    address: '1515, boulevard du Tricentenaire, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-rodrigue-gilbert',
    sources: montreal('arena-rodrigue-gilbert'),
  },
  {
    id: 'montreal-rolland',
    name: 'Aréna Rolland',
    town: 'Montréal (Montréal-Nord)', state: 'QC', region: 'Montréal',
    address: '12000, boulevard Rolland, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-rolland',
    sources: montreal('arena-rolland'),
  },
  {
    id: 'montreal-saint-charles',
    name: 'Aréna Saint-Charles',
    town: 'Montréal (Le Sud-Ouest)', state: 'QC', region: 'Montréal',
    address: '1055, rue d\'Hibernia, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-saint-charles',
    sources: montreal('arena-saint-charles'),
  },
  {
    id: 'montreal-saint-donat',
    name: 'Aréna Saint-Donat',
    town: 'Montréal (Mercier–Hochelaga-Maisonneuve)', state: 'QC', region: 'Montréal',
    address: '6750, rue de Marseille, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-saint-donat',
    sources: montreal('arena-saint-donat'),
  },
  {
    id: 'montreal-sylvio-mantha',
    name: 'Aréna Sylvio-Mantha',
    town: 'Montréal (Le Sud-Ouest)', state: 'QC', region: 'Montréal',
    address: '5485, chemin de la Côte-Saint-Paul, Montréal, QC',
    website: 'https://montreal.ca/lieux/arena-sylvio-mantha',
    sources: montreal('arena-sylvio-mantha'),
  },
  {
    id: 'quebec-city-arenas',
    name: 'Ville de Québec arenas',
    town: 'Québec', state: 'QC', region: 'Québec City',
    website: 'https://www.ville.quebec.qc.ca/citoyens/loisirs_sports/sports/patinage.aspx',
    note: 'Patinage libre and hockey libre at city arenas.',
  },

  // ================= British Columbia =================
  {
    id: 'vancouver-britannia',
    name: 'Britannia Rink',
    town: 'Vancouver', state: 'BC', region: 'Vancouver',
    website: 'https://vancouver.ca/parks-recreation-culture/ice-rinks.aspx',
    sources: vancouver(24),
    note: 'Vancouver Park Board. Public skate, public hockey, and stick, puck & ring.',
  },
  {
    id: 'vancouver-hillcrest',
    name: 'Hillcrest Rink',
    town: 'Vancouver', state: 'BC', region: 'Vancouver',
    website: 'https://vancouver.ca/parks-recreation-culture/ice-rinks.aspx',
    sources: vancouver(22),
    note: 'Vancouver Park Board. Public skate, public hockey, and stick, puck & ring.',
  },
  {
    id: 'vancouver-kerrisdale-cyclone-taylor',
    name: 'Kerrisdale Cyclone Taylor Arena',
    town: 'Vancouver', state: 'BC', region: 'Vancouver',
    website: 'https://vancouver.ca/parks-recreation-culture/ice-rinks.aspx',
    sources: vancouver(23),
    note: 'Vancouver Park Board. Public skate, public hockey, and stick, puck & ring.',
  },
  {
    id: 'vancouver-killarney',
    name: 'Killarney Rink',
    town: 'Vancouver', state: 'BC', region: 'Vancouver',
    website: 'https://vancouver.ca/parks-recreation-culture/ice-rinks.aspx',
    sources: vancouver(25),
    note: 'Vancouver Park Board. Public skate, public hockey, and stick, puck & ring.',
  },
  {
    id: 'vancouver-kitsilano',
    name: 'Kitsilano Rink',
    town: 'Vancouver', state: 'BC', region: 'Vancouver',
    website: 'https://vancouver.ca/parks-recreation-culture/ice-rinks.aspx',
    sources: vancouver(26),
    note: 'Vancouver Park Board. Public skate, public hockey, and stick, puck & ring.',
  },
  {
    id: 'vancouver-sunset',
    name: 'Sunset Rink',
    town: 'Vancouver', state: 'BC', region: 'Vancouver',
    website: 'https://vancouver.ca/parks-recreation-culture/ice-rinks.aspx',
    sources: vancouver(27),
    note: 'Vancouver Park Board. Public skate, public hockey, and stick, puck & ring.',
  },
  {
    id: 'vancouver-trout-lake',
    name: 'Trout Lake Rink',
    town: 'Vancouver', state: 'BC', region: 'Vancouver',
    website: 'https://vancouver.ca/parks-recreation-culture/ice-rinks.aspx',
    sources: vancouver(28),
    note: 'Vancouver Park Board. Public skate, public hockey, and stick, puck & ring.',
  },
  {
    id: 'vancouver-west-end',
    name: 'West End Rink',
    town: 'Vancouver', state: 'BC', region: 'Vancouver',
    website: 'https://vancouver.ca/parks-recreation-culture/ice-rinks.aspx',
    sources: vancouver(9),
    note: 'Vancouver Park Board. Public skate, public hockey, and stick, puck & ring.',
  },
  {
    id: 'canlan-burnaby',
    name: 'Canlan Scotia Barn',
    town: 'Burnaby', state: 'BC', region: 'Metro Vancouver',
    website: 'https://www.canlansports.com/',
    sources: [{ type: 'daysmart', company: 'canlan', resourceIds: [1, 2], exclude: /goalies/i }],
    note: 'Canlan Sports. Stick & puck; mostly league ice.',
  },
  {
    id: 'canlan-langley',
    name: 'Canlan Langley Twin Rinks',
    town: 'Langley', state: 'BC', region: 'Metro Vancouver',
    website: 'https://www.canlansports.com/',
    sources: [{ type: 'daysmart', company: 'canlan', resourceIds: [202, 203], exclude: /goalies/i }],
    note: 'Canlan Sports. Adult, teen and family stick & puck.',
  },
  {
    id: 'canlan-north-shore',
    name: 'Canlan North Shore',
    town: 'North Vancouver', state: 'BC', region: 'Metro Vancouver',
    website: 'https://www.canlansports.com/',
    sources: [{ type: 'daysmart', company: 'canlan', resourceIds: [277, 278, 279], exclude: /goalies/i }],
    note: 'Canlan Sports. Stick & puck, shinny and figure skating open.',
  },
  {
    id: 'ubc-thunderbird',
    name: 'UBC Thunderbird Arena',
    town: 'Vancouver', state: 'BC', region: 'Vancouver',
    website: 'https://recreation.ubc.ca/ice/drop-in-ice/',
    note: 'Drop-in skating and hockey at UBC.',
  },
  {
    id: 'north-van-arenas',
    name: 'North Vancouver Recreation arenas',
    town: 'North Vancouver', state: 'BC', region: 'Metro Vancouver',
    website: 'https://www.nvrc.ca/facilities-fields/locations-hours/arenas',
  },

  // ================= Alberta =================
  {
    id: 'calgary-southland',
    name: 'Southland Leisure Centre',
    town: 'Calgary', state: 'AB', region: 'Calgary',
    website: 'https://liveandplay.calgary.ca/REGPROG/public/category/browse/PublicSkate',
    sources: calgary(['Southland - Ed Whalen Arena', 'Southland - Joseph Kryczka Arena']),
    note: 'City of Calgary public skate and shinny. Book a spot online.',
  },
  {
    id: 'calgary-village-square',
    name: 'Village Square Leisure Centre (Wally Kozak Arena)',
    town: 'Calgary', state: 'AB', region: 'Calgary',
    website: 'https://liveandplay.calgary.ca/REGPROG/public/category/browse/PublicSkate',
    sources: calgary('Village Square - Wally Kozak Arena'),
    note: 'City of Calgary public skate and shinny. Book a spot online.',
  },
  {
    id: 'calgary-henry-viney',
    name: 'Henry Viney Arena',
    town: 'Calgary', state: 'AB', region: 'Calgary',
    website: 'https://liveandplay.calgary.ca/REGPROG/public/category/browse/PublicSkate',
    sources: calgary('Henry Viney Arena'),
    note: 'City of Calgary public skate and shinny. Book a spot online.',
  },
  {
    id: 'calgary-murray-copot',
    name: 'Murray Copot Arena',
    town: 'Calgary', state: 'AB', region: 'Calgary',
    website: 'https://liveandplay.calgary.ca/REGPROG/public/category/browse/PublicSkate',
    sources: calgary('Murray Copot Arena'),
    note: 'City of Calgary public skate and shinny. Book a spot online.',
  },
  {
    id: 'calgary-george-blundun',
    name: 'George Blundun Arena',
    town: 'Calgary', state: 'AB', region: 'Calgary',
    website: 'https://liveandplay.calgary.ca/REGPROG/public/category/browse/PublicSkate',
    sources: calgary('George Blundun Arena'),
    note: 'City of Calgary public skate and shinny. Book a spot online.',
  },
  {
    id: 'calgary-rose-kohn',
    name: 'Rose Kohn Arena',
    town: 'Calgary', state: 'AB', region: 'Calgary',
    website: 'https://liveandplay.calgary.ca/REGPROG/public/category/browse/PublicSkate',
    sources: calgary('Rose Kohn Arena'),
    note: 'City of Calgary public skate and shinny. Book a spot online.',
  },
  {
    id: 'calgary-stew-hendry',
    name: 'Stew Hendry Arena',
    town: 'Calgary', state: 'AB', region: 'Calgary',
    website: 'https://liveandplay.calgary.ca/REGPROG/public/category/browse/PublicSkate',
    sources: calgary('Stew Hendry Arena'),
    note: 'City of Calgary public skate and shinny. Book a spot online.',
  },
  {
    id: 'calgary-jimmie-condon',
    name: 'Jimmie Condon Arena',
    town: 'Calgary', state: 'AB', region: 'Calgary',
    website: 'https://liveandplay.calgary.ca/REGPROG/public/category/browse/PublicSkate',
    sources: calgary('Jimmie Condon Arena'),
    note: 'City of Calgary public skate and shinny. Book a spot online.',
  },
  {
    id: 'calgary-stu-peppard',
    name: 'Stu Peppard Arena',
    town: 'Calgary', state: 'AB', region: 'Calgary',
    website: 'https://liveandplay.calgary.ca/REGPROG/public/category/browse/PublicSkate',
    sources: calgary('Stu Peppard Arena'),
    note: 'City of Calgary public skate and shinny. Book a spot online.',
  },
  {
    id: 'calgary-shouldice',
    name: 'Shouldice Arena',
    town: 'Calgary', state: 'AB', region: 'Calgary',
    website: 'https://liveandplay.calgary.ca/REGPROG/public/category/browse/PublicSkate',
    sources: calgary('Shouldice Arena'),
    note: 'City of Calgary public skate and shinny. Book a spot online.',
  },
  {
    id: 'calgary-optimist',
    name: 'Optimist Arena',
    town: 'Calgary', state: 'AB', region: 'Calgary',
    website: 'https://liveandplay.calgary.ca/REGPROG/public/category/browse/PublicSkate',
    sources: calgary('Optimist Arena'),
    note: 'City of Calgary public skate and shinny. Book a spot online.',
  },
  {
    id: 'edmonton-city-arenas',
    name: 'City of Edmonton arenas',
    town: 'Edmonton', state: 'AB', region: 'Edmonton',
    website: 'https://movelearnplay.edmonton.ca/COE/public/category/browse/RECARENA',
    note: 'Public skating at 22 city arenas; book up to two weeks ahead on move.learn.play or call 311.',
  },
  {
    id: 'kinsmen-edmonton',
    name: 'Kinsmen Arenas',
    town: 'Edmonton', state: 'AB', region: 'Edmonton',
    website: 'https://www.kinsmenarenas.com/public-skating',
  },

  // ================= Manitoba =================
  {
    id: 'canlan-winnipeg',
    name: 'Canlan Winnipeg',
    town: 'Winnipeg', state: 'MB', region: 'Winnipeg',
    website: 'https://www.canlansports.com/',
    sources: [{ type: 'daysmart', company: 'canlan', resourceIds: [151, 152, 153], exclude: /goalies/i }],
    note: 'Canlan Sports. Public skating and stick & puck.',
  },
  {
    id: 'winnipeg-city-arenas',
    name: 'City of Winnipeg arenas',
    town: 'Winnipeg', state: 'MB', region: 'Winnipeg',
    website: 'https://www.winnipeg.ca/recreation-leisure/recreation-programs/free-programs/skating',
    note: 'Free public skating at city arenas, late September to March.',
  },
  {
    id: 'garden-city-cc',
    name: 'Garden City Community Centre',
    town: 'Winnipeg', state: 'MB', region: 'Winnipeg',
    website: 'https://www.gardencitycc.com/arena/publicskating',
  },
  {
    id: 'east-end-arena',
    name: 'Transcona East End Community Centre',
    town: 'Winnipeg', state: 'MB', region: 'Winnipeg',
    website: 'https://eastendarena.ca/public_skating',
  },

  // ================= Saskatchewan =================
  {
    id: 'saskatoon-city-arenas',
    name: 'City of Saskatoon arenas',
    town: 'Saskatoon', state: 'SK', region: 'Saskatoon',
    website: 'https://dropinschedule.saskatoon.ca/',
    note: 'Public and parent & tot skating at ACT, Lions, Cosmo and Archibald arenas.',
  },
  {
    id: 'regina-city-arenas',
    name: 'City of Regina arenas',
    town: 'Regina', state: 'SK', region: 'Regina',
    website: 'https://www.regina.ca/parks-recreation-culture/recreation-facilities/skating-rinks/',
    note: 'Public skate times are posted as a PDF, September to March.',
  },
  {
    id: 'cooperators-centre-regina',
    name: 'Co-operators Centre',
    town: 'Regina', state: 'SK', region: 'Regina',
    website: 'https://www.realdistrict.ca/public-skate-schedule/',
  },

  // ================= Nova Scotia =================
  {
    id: 'halifax-forum',
    name: 'Halifax Forum',
    town: 'Halifax', state: 'NS', region: 'Halifax',
    website: 'https://www.halifaxforum.ca/public-skates/',
    note: 'Free public skating Monday and Friday at noon, September to March.',
  },
  {
    id: 'rbc-centre-dartmouth',
    name: 'RBC Centre',
    town: 'Dartmouth', state: 'NS', region: 'Halifax',
    phone: '902-444-4723',
    website: 'https://www.rbccentredartmouth.com/schedules',
  },
  {
    id: 'sackville-sports-stadium',
    name: 'Sackville Sports Stadium',
    town: 'Lower Sackville', state: 'NS', region: 'Halifax',
    phone: '902-869-4141',
    website: 'https://thestadium.ca/index.php/schedules-main/skating-schedule',
  },
  {
    id: 'emera-oval',
    name: 'Emera Oval (outdoor, seasonal)',
    town: 'Halifax', state: 'NS', region: 'Halifax',
    website: 'https://www.halifax.ca/parks-recreation/programs-activities/outdoor-recreation/emera-oval',
  },

  // ================= New Brunswick =================
  {
    id: 'moncton-arenas',
    name: 'City of Moncton arenas',
    town: 'Moncton', state: 'NB', region: 'Moncton',
    website: 'https://www.moncton.ca/en/publicskating',
    note: 'Public skating at the Greenfoot Energy 4-Plex, Kay Arena and the Coliseum. CSA hockey helmets required.',
  },
  {
    id: 'saint-john-arenas',
    name: 'City of Saint John arenas',
    town: 'Saint John', state: 'NB', region: 'Saint John',
    website: 'https://saintjohn.ca/en/parks-and-recreation/arenas-and-skating',
    note: 'Free public skating at Charles Gorman, Stewart Hurley and Peter Murray arenas, October to March.',
  },
  {
    id: 'fredericton-arenas',
    name: 'City of Fredericton arenas',
    town: 'Fredericton', state: 'NB', region: 'Fredericton',
    website: 'https://www.fredericton.ca/recreation-leisure/facilities-rentals/arenas-outdoor-rinks',
    note: 'Public skates for all ages, plus adult, senior and preschool sessions.',
  },

  // ================= Prince Edward Island =================
  {
    id: 'charlottetown-arenas',
    name: 'City of Charlottetown arenas',
    town: 'Charlottetown', state: 'PE', region: 'Charlottetown',
    website: 'https://www.charlottetown.ca/',
    note: 'Public skating at city arenas; check the city recreation pages for times.',
  },

  // ================= Newfoundland and Labrador (Newfoundland time) =================
  {
    id: 'st-johns-arenas',
    name: 'City of St. John\'s arenas',
    town: 'St. John\'s', state: 'NL', region: 'St. John\'s',
    website: 'https://www.stjohns.ca/',
    note: 'Public skating at city arenas; check the City of St. John\'s recreation pages for times.',
  },
];
