// Rink registry.
//
// Every rink has a `state` code from STATES. A state's `slug` is its web address
// (calarink.com/maine); the build writes a page for each one.
//
// source.type:
//   'ics'      – iCalendar feed (public Google Calendars work: .../calendar/ical/<id>/public/basic.ics)
//   'finnly'   – Finnly Connect public schedule page
//   'pageText' – schedule posted as text on a web page (dated lines, optional weekly lines)
//   none       – no machine-readable schedule; shown as a "check directly" card
//
// To add a rink, append an entry. `id` must be unique and stable (it's used in the URL filters).

const gcal = id => `https://calendar.google.com/calendar/ical/${encodeURIComponent(id)}/public/basic.ics`;

// `tz` is the state's time zone: schedules that give local times are read in it, and the
// site shows that state's times in it. `default` is the state a first-time visitor sees.
export const STATES = [
  { code: 'CT', slug: 'connecticut', name: 'Connecticut', tz: 'America/New_York' },
  { code: 'ME', slug: 'maine', name: 'Maine', tz: 'America/New_York', default: true },
  { code: 'MA', slug: 'massachusetts', name: 'Massachusetts', tz: 'America/New_York' },
  { code: 'MN', slug: 'minnesota', name: 'Minnesota', tz: 'America/Chicago' },
  { code: 'NH', slug: 'new-hampshire', name: 'New Hampshire', tz: 'America/New_York' },
  { code: 'RI', slug: 'rhode-island', name: 'Rhode Island', tz: 'America/New_York' },
];

export const RINKS = [
  {
    id: 'usm-gorham',
    name: 'USM Ice Arena',
    town: 'Gorham', state: 'ME', region: 'Southern',
    website: 'https://usm.maine.edu/ice-arena/hours/',
    sources: [{ type: 'ics', url: gcal('usmicearena@maine.edu') }],
    note: 'Full arena calendar. "Student Open Skate" is USM-only.',
  },
  {
    id: 'ice-vault-hallowell',
    name: 'Thomas College Ice Vault',
    town: 'Hallowell', state: 'ME', region: 'Central',
    address: '203 Whitten Rd, Hallowell, ME',
    website: 'https://www.maineicevault.com/',
    scheduleUrl: 'https://tciv.finnlyconnect.com/schedule/612',
    sources: [{ type: 'finnly', url: 'https://tciv.finnlyconnect.com/schedule/612' }],
    note: 'Public skate $10, rentals $6. Weekend sessions often sell out — buy online.',
  },
  {
    id: 'alfond-orono',
    name: 'Alfond Arena (UMaine)',
    town: 'Orono', state: 'ME', region: 'Northern & Downeast',
    website: 'https://umaine.edu/campusrecreation/facilities__trashed/alfond-arena/',
    sources: [{ type: 'ics', url: gcal('o84kduv0jjtn8siju6nu5i9ueg@group.calendar.google.com') }],
    note: 'Public skate & stick-and-puck calendar only (Campus Rec). Stick & Puck is 18+.',
  },
  {
    id: 'pia-brewer',
    name: 'Penobscot Ice Arena (PIA)',
    town: 'Brewer', state: 'ME', region: 'Northern & Downeast',
    address: '90 Acme Rd, Brewer, ME', phone: '207-989-7183',
    website: 'https://www.penobscoticearena.com/',
    sources: [{ type: 'ics', url: gcal('m3mm3gbf0u02ko5jcg9r7c091k@group.calendar.google.com') }],
    note: 'Full arena calendar. Some stick n puck sessions are age-split (13 & under / 14 & over).',
  },
  {
    id: 'pcia-dover-foxcroft',
    name: 'Piscataquis County Ice Arena (PCIA)',
    town: 'Dover-Foxcroft', state: 'ME', region: 'Northern & Downeast',
    address: '1049 W Main St, Dover-Foxcroft, ME',
    website: 'https://www.thepcia.com/public-skate.html',
    scheduleUrl: 'https://pcia.finnlyconnect.com/schedule/903',
    sources: [{ type: 'finnly', url: 'https://pcia.finnlyconnect.com/schedule/903' }],
    note: 'Public skate $10, walk-ins welcome; skate rental $3. "Stick Time" is their stick & puck.',
  },
  {
    id: 'forum-presque-isle',
    name: 'The Forum',
    town: 'Presque Isle', state: 'ME', region: 'Northern & Downeast',
    phone: '207-764-0491',
    website: 'https://www.thepiforum.org/',
    sources: [{ type: 'ics', url: 'https://outlook.office365.com/owa/calendar/0069475393ca4306b04019da8c33ab28@presqueisleme.us/815093ea02cb4d868f4e76c2f0ebcc8c8151721194698282749/calendar.ics' }],
    note: 'Full arena calendar (City of Presque Isle Outlook calendar). Public skate $7, rentals $5. Times can change for hockey games — call to confirm.',
  },
  {
    id: 'casco-bay-falmouth',
    name: 'Casco Bay Arena',
    town: 'Falmouth', state: 'ME', region: 'Southern',
    website: 'https://cascobayarena.com/ice-schedule-2/',
    sources: [{ type: 'ics', url: gcal('12qbntcc8t3cgl39lde3pm54ao@group.calendar.google.com') }],
    note: 'Arena master schedule. Mostly team ice; "OPEN" = unbooked ice, not a public session.',
  },
  {
    id: 'nsb-auburn',
    name: 'Norway Savings Bank Arena',
    town: 'Auburn', state: 'ME', region: 'Central',
    address: '985 Turner St, Auburn, ME',
    website: 'https://www.norwaysavingsbankarena.com/page/show/8447987-drop-in-recreational-programming',
    sources: [
      { type: 'pageText', title: 'Public Skate', url: 'https://www.norwaysavingsbankarena.com/page/show/7694782-public-skate-', projectWeekly: 6 },
      { type: 'pageText', title: 'Shinny Hockey', url: 'https://www.norwaysavingsbankarena.com/page/show/8023693-shinny-hockey-schedule-' },
    ],
    note: 'Read from the arena\'s posted text. Public skate $5; shinny $10. Changes often — check the site.',
  },

  // ---- No machine-readable schedule: shown as "check directly" ----
  {
    id: 'troubh-portland',
    name: 'Troubh Ice Arena',
    town: 'Portland', state: 'ME', region: 'Southern',
    address: '225 Park Ave, Portland, ME', phone: '207-774-8553',
    website: 'https://www.portlandmaine.gov/528/William-B-Troubh-Ice-Arena',
    note: 'Public skate calendar is posted as a monthly PDF.',
  },
  {
    id: 'colisee-lewiston',
    name: 'The Colisée',
    town: 'Lewiston', state: 'ME', region: 'Central',
    address: '190 Birch St, Lewiston, ME', phone: '207-783-2009',
    website: 'https://www.thecolisee.com/',
  },
  {
    id: 'sawyer-bangor',
    name: 'Sawyer Arena',
    town: 'Bangor', state: 'ME', region: 'Northern & Downeast',
    address: '107 13th St, Bangor, ME', phone: '207-947-0071',
    website: 'https://www.bangormaine.gov/676/Sawyer-Arena',
    note: 'Closed for the off-season; reopens October 2026. Public skate times are posted as PDFs on Bangor Parks & Rec (bangorme.myrec.com) and Facebook.',
  },
  {
    id: 'midcoast-rockport',
    name: 'Midcoast Recreation Center',
    town: 'Rockport', state: 'ME', region: 'Midcoast',
    address: '535 West St, Rockport, ME', phone: '207-236-9400',
    website: 'https://www.midcoastrec.org/public-skate',
    scheduleUrl: 'https://book.midcoastrec.org/Online/Public/EmbedCode/16147/58434?customId=125636',
    note: 'Arena schedule is a live CourtReserve calendar (not scrapeable without a browser).',
  },
  {
    id: 'biddeford',
    name: 'Biddeford Ice Arena',
    town: 'Biddeford', state: 'ME', region: 'Southern',
    address: '14 Pomerleau St, Biddeford, ME', phone: '207-283-0615',
    website: 'https://biddefordarena.com/public-skating',
    note: 'Public skating is limited; they post times on Facebook.',
  },
  {
    id: 'family-ice-falmouth',
    name: 'Family Ice Center',
    town: 'Falmouth', state: 'ME', region: 'Southern',
    address: '20 Hat Trick Dr, Falmouth, ME', phone: '207-781-4200',
    website: 'https://familyice.org/programs/public-skating/',
    note: 'Outdoor pond only, early Dec – late Feb, 10am–9pm daily, weather permitting. Free. No indoor public skate.',
  },
  {
    id: 'travis-roy-yarmouth',
    name: 'Travis Roy Ice Arena (NYA)',
    town: 'Yarmouth', state: 'ME', region: 'Southern',
    website: 'https://www.facebook.com/NYATravisRoyArena/',
  },
  {
    id: 'thompsons-point',
    name: "The Rink at Thompson's Point (outdoor, seasonal)",
    town: 'Portland', state: 'ME', region: 'Southern',
    website: 'https://www.thompsonspointrink.com/iceschedule',
  },

  // ================= Massachusetts =================
  {
    id: 'warrior-boston',
    name: 'Warrior Ice Arena',
    town: 'Boston (Brighton)', state: 'MA', region: 'Boston Area',
    address: '90 Guest St, Boston, MA',
    website: 'https://www.warrioricearena.com/public-sessions/',
    scheduleUrl: 'https://warrior.finnlyconnect.com/schedule/19',
    sources: [{ type: 'finnly', url: 'https://warrior.finnlyconnect.com/schedule/19' }],
    note: 'Bruins practice facility. Public skate $16 weekdays, $18 weekends (skate rental included).',
  },
  {
    id: 'canton-ice-house',
    name: 'Canton Ice House',
    town: 'Canton', state: 'MA', region: 'South Shore & South',
    website: 'https://www.cantonicehouse.com/',
    scheduleUrl: 'https://cih.finnlyconnect.com/schedule/594',
    sources: [{ type: 'finnly', url: 'https://cih.finnlyconnect.com/schedule/594' }],
    note: 'Full arena schedule. Mostly team ice; freestyle sessions are listed.',
  },
  {
    id: 'rodman-walpole',
    name: 'Rodman Arena',
    town: 'Walpole', state: 'MA', region: 'South Shore & South',
    address: '2130 Providence Hwy, Walpole, MA',
    website: 'https://www.rodmanarena.com/',
    sources: [
      { type: 'ics', url: gcal('d6367ea5971e44b01054cd0be45b3d31d51750301807bea35a4222fd0e3455ec@group.calendar.google.com') },
      { type: 'ics', url: gcal('0e071d4ca0f264df1bdf6ef6a5507f0771ac06655475640e3d52f1772be234dc@group.calendar.google.com') },
    ],
    note: 'Public skating $7 adults, $5 under 10. Public hockey $8, ages 14+, helmet and gloves required.',
  },
  {
    id: 'talbot-gloucester',
    name: 'Talbot Rink',
    town: 'Gloucester', state: 'MA', region: 'North Shore',
    address: '31 Cherry St, Gloucester, MA',
    website: 'https://talbotrink.gloucester-ma.gov/',
    sources: [{ type: 'ics', url: gcal('c_5sfgegqoa0900b84c6alefte18@group.calendar.google.com') }],
    note: 'Full rink calendar. Public skating Sundays, mid-November through March; adult stick practice and adult skate Wednesday mornings.',
  },
  {
    id: 'stoneham-arena',
    name: 'Stoneham Arena',
    town: 'Stoneham', state: 'MA', region: 'Boston Area',
    website: 'https://www.stoneham-ma.gov/164/Stoneham-Arena',
    note: 'Public skating, adult stick practice and freestyle. Stick practice and freestyle require pre-registration by email.',
  },
  {
    id: 'edge-bedford',
    name: 'The Edge Sports Center',
    town: 'Bedford', state: 'MA', region: 'Boston Area',
    address: '191 Hartwell Ave, Bedford, MA',
    website: 'https://theedgesportscenter.com/services/public-skating/',
  },
  {
    id: 'pilgrim-hingham',
    name: 'Pilgrim Skating Arena',
    town: 'Hingham', state: 'MA', region: 'South Shore & South',
    address: '75 Recreation Park Dr, Hingham, MA',
    website: 'https://www.pilgrimarena.com/',
  },
  {
    id: 'olympia-west-springfield',
    name: 'Olympia Ice Center',
    town: 'West Springfield', state: 'MA', region: 'Western',
    website: 'https://www.olympiaicecenter.com/',
  },
  {
    id: 'dcr-rinks',
    name: 'DCR state rinks',
    town: 'Statewide', state: 'MA', region: 'Boston Area',
    website: 'https://www.mass.gov/info-details/dcr-ice-skating-rink-schedule',
    note: 'The state runs about 15 rinks, mostly around Boston. Public skating runs late November to mid-April, with public stick time at some rinks. Hours for each rink are on this page.',
  },

  // ================= New Hampshire =================
  {
    id: 'everett-concord',
    name: 'Everett Arena',
    town: 'Concord', state: 'NH', region: 'Central & Lakes',
    website: 'https://concordnh.gov/921/Ice-Skating-Stick-Practice',
    scheduleUrl: 'https://everett.finnlyconnect.com/schedule/1005',
    sources: [{ type: 'finnly', url: 'https://everett.finnlyconnect.com/schedule/1005' }],
    note: 'City-run. Season mid-September to mid-March. Stick practice is also offered; check the city page for hours.',
  },
  {
    id: 'keene-ice',
    name: 'Keene Ice',
    town: 'Keene', state: 'NH', region: 'West & North',
    website: 'https://www.keeneice.com/',
    scheduleUrl: 'https://keene.finnlyconnect.com/schedule/91',
    sources: [{ type: 'finnly', url: 'https://keene.finnlyconnect.com/schedule/91' }],
    note: 'Public skate $8, rentals $5. Adult stick time $12, full gear required.',
  },
  {
    id: 'campion-hanover',
    name: 'Campion Rink',
    town: 'Hanover', state: 'NH', region: 'West & North',
    website: 'https://www.campionrink.org/',
    sources: [{ type: 'daysmart', company: 'hanover' }],
    note: 'Full rink schedule. "Open Stick" is their stick & puck.',
  },
  {
    id: 'merrill-fay-laconia',
    name: 'Merrill Fay Arena',
    town: 'Laconia', state: 'NH', region: 'Central & Lakes',
    address: '468 Province Rd, Laconia, NH',
    website: 'https://merrillfayarena.com/',
    note: 'Public skating Saturdays and Sundays, 2:00–3:30 PM, from September. Also stick and puck and "Power Hour".',
  },
  {
    id: 'ham-arena-conway',
    name: 'Ham Arena',
    town: 'Conway', state: 'NH', region: 'West & North',
    website: 'https://hamarena.com/public-hours/',
    note: 'Non-profit rink. Public skating and stick & puck every week; schedules linked from this page.',
  },
  {
    id: 'conway-arena-nashua',
    name: 'Conway Arena',
    town: 'Nashua', state: 'NH', region: 'Southern',
    website: 'https://conwayarena.com/',
    note: 'Public skate, stick practice and freestyle; buy admission online.',
  },
  {
    id: 'jfk-manchester',
    name: 'JFK Coliseum',
    town: 'Manchester', state: 'NH', region: 'Southern',
    website: 'https://www.manchesternh.gov/Departments/Parks-and-Recreation/Programs-and-Activities/Activities/Ice-Skating',
    note: 'City-run. Public skating generally Tuesday and Thursday mornings and weekend afternoons, October–March. Stick & puck is at West Side Arena.',
  },

  // ================= Rhode Island =================
  {
    id: 'cvm-cranston',
    name: 'Cranston Veterans Memorial Rink',
    town: 'Cranston', state: 'RI', region: 'Providence Area',
    website: 'https://www.cvmrink.com/public',
    sources: [
      { type: 'ics', url: gcal('a2f5d1296a00a288bae699cf743e11f902fcba21604427a2d38421ed059720c2@group.calendar.google.com') },
      { type: 'ics', url: gcal('13e1f59521b50f503295cd8a2fad040c16a5f5e244033ef5874cdec3f2a90a0f@group.calendar.google.com') },
      { type: 'ics', url: gcal('23693dd81aaf7826cbd378dc2abe175bdc20485bdcffa16b992261f10dc8efde@group.calendar.google.com') },
      { type: 'ics', url: gcal('8f6fc3a6b1030569b801add9c6a18b34b5fd197074b977dbda567b170ce2077b@group.calendar.google.com') },
    ],
    note: 'Public skating $10 (cash only). Times change often; the rink asks you to check the day you go.',
  },
  {
    id: 'risc-north-smithfield',
    name: 'Rhode Island Sports Center',
    town: 'North Smithfield', state: 'RI', region: 'Northern RI',
    address: '1186 Eddie Dowling Hwy, North Smithfield, RI',
    website: 'https://www.risportscenter.com/',
    scheduleUrl: 'https://risc.finnlyconnect.com/schedule/179',
    sources: [{ type: 'finnly', url: 'https://risc.finnlyconnect.com/schedule/179' }],
    note: 'Full arena schedule. Mostly team ice.',
  },
  {
    id: 'providence-rink',
    name: 'The Providence Rink (outdoor, seasonal)',
    town: 'Providence', state: 'RI', region: 'Providence Area',
    address: '2 Kennedy Plaza, Providence, RI',
    website: 'https://theprovidencerink.com/',
  },
  {
    id: 'smithfield-ri',
    name: 'Smithfield Municipal Ice Rink',
    town: 'Smithfield', state: 'RI', region: 'Northern RI',
    website: 'https://www.smithfieldri.gov/departments/ice-rink',
  },
  {
    id: 'benny-magiera',
    name: 'Benny Magiera Ice Rink',
    town: 'West Warwick', state: 'RI', region: 'Kent County',
    website: 'https://westwarwickri.gov/?SEC=706EFDDE-B8A8-457B-8035-C96BC10019E1',
    note: 'Stick and puck sessions; under-18s need an adult present in the rink.',
  },

  // ================= Connecticut =================
  {
    id: 'sportscenter-shelton',
    name: 'SportsCenter of Connecticut',
    town: 'Shelton', state: 'CT', region: 'Fairfield County',
    website: 'https://www.sportscenterct.com/skate-hours/',
    scheduleUrl: 'https://scc.finnlyconnect.com/schedule/374',
    sources: [{ type: 'finnly', url: 'https://scc.finnlyconnect.com/schedule/374' }],
    note: 'Double-decker NHL rinks. Public skate, stick & puck and freestyle schedule.',
  },
  {
    id: 'stamford-twin-rinks',
    name: 'Stamford Twin Rinks',
    town: 'Stamford', state: 'CT', region: 'Fairfield County',
    website: 'https://stamfordtwinrinks.com/',
    sources: [{ type: 'daysmart', company: 'stamford' }],
  },
  {
    id: 'iscc-simsbury',
    name: 'International Skating Center of CT',
    town: 'Simsbury', state: 'CT', region: 'Hartford Area',
    website: 'https://www.isccskate.com/events/public-skate/9833',
    scheduleUrl: 'https://iscc.finnlyconnect.com/schedule/558',
    sources: [{ type: 'finnly', url: 'https://iscc.finnlyconnect.com/schedule/558' }],
    note: 'Public skate $10, rentals $5; usually Friday nights and weekends. "Stick Time" is their stick & puck.',
  },
  {
    id: 'danbury-ice',
    name: 'Danbury Ice Arena',
    town: 'Danbury', state: 'CT', region: 'Fairfield County',
    address: '1 Independence Way, Danbury, CT',
    website: 'https://danburyice.com/public-sessions/',
    note: 'Twin rinks, open seven days a week. Public skate and sticks & pucks.',
  },
  {
    id: 'enfield-twin-rinks',
    name: 'Enfield Twin Rinks',
    town: 'Enfield', state: 'CT', region: 'Hartford Area',
    address: '1 Prior Rd, Enfield, CT',
    website: 'https://www.etrinks.com/',
  },
  {
    id: 'bolton-ice-palace',
    name: 'Bolton Ice Palace',
    town: 'Bolton', state: 'CT', region: 'Hartford Area',
    address: '145 Hop River Rd, Bolton, CT',
    website: 'https://www.boltonicepalace.com/',
  },
  {
    id: 'champions-cromwell',
    name: 'Champions Skating Center',
    town: 'Cromwell', state: 'CT', region: 'Hartford Area',
    address: '6 Progress Dr, Cromwell, CT',
    website: 'https://www.championsskatingcenter.com/',
  },
  {
    id: 'newington-arena',
    name: 'Newington Arena',
    town: 'Newington', state: 'CT', region: 'Hartford Area',
    address: '300 Alumni Rd, Newington, CT',
    website: 'https://www.newingtonarena.com/',
  },

  // ================= Minnesota (Central time) =================
  {
    id: 'super-rink-blaine',
    name: 'Super Rink (National Sports Center)',
    town: 'Blaine', state: 'MN', region: 'Twin Cities North',
    website: 'https://nscsports.org/facilities/superrink/',
    scheduleUrl: 'https://nationalsportscenter.finnlyconnect.com/schedule/80',
    sources: [{ type: 'finnly', url: 'https://nationalsportscenter.finnlyconnect.com/schedule/80' }],
    note: 'Eight sheets of ice. Full schedule; public and senior skates are listed.',
  },
  {
    id: 'andover-community-center',
    name: 'Andover Community Center',
    town: 'Andover', state: 'MN', region: 'Twin Cities North',
    website: 'https://www.andovermn.gov/335/Open-Skate',
    scheduleUrl: 'https://acc.finnlyconnect.com/schedule/956',
    sources: [{ type: 'finnly', url: 'https://acc.finnlyconnect.com/schedule/956' }],
    note: 'No sticks, pucks or figure-skating jumps during open skate.',
  },
  {
    id: 'parade-minneapolis',
    name: 'Parade Ice Garden',
    town: 'Minneapolis', state: 'MN', region: 'Minneapolis & St. Paul',
    website: 'https://www.minneapolisparks.org/activities-events/winter_activities/ice_rinks/parade_ice_garden/',
    sources: [
      { type: 'finnly', url: 'https://parade.finnlyconnect.com/schedule/145' },
      { type: 'finnly', url: 'https://parade.finnlyconnect.com/schedule/146' },
    ],
    note: 'Open skating $5 ($3 seniors, under 5 free). Adult open hockey: max 20 skaters + 2 goalies; goalies call in at 8 AM that day.',
  },
  {
    id: 'maple-grove',
    name: 'Maple Grove Community Center Ice Arena',
    town: 'Maple Grove', state: 'MN', region: 'Twin Cities West & South',
    website: 'https://www.maplegrovemn.gov/274/Ice-arena',
    sources: [
      { type: 'ics', url: gcal('9b8a801985b58adc2d74b2b6fa721ee8459a0967e842fd0dd31f2b32860f3f78@group.calendar.google.com') },
      { type: 'ics', url: gcal('c6418d02ceed0913644d69da65495d46a48a967a56f6944838f5eda2ee7d3518@group.calendar.google.com') },
      { type: 'ics', url: gcal('0d85236c4d82201240ca21704e7f112a8ac9b591d183c6d1dfa1fa5a7c6eaaf7@group.calendar.google.com') },
    ],
    note: 'Open skate, adult open hockey and senior open hockey calendars.',
  },
  {
    id: 'plymouth-ice-center',
    name: 'Plymouth Ice Center',
    town: 'Plymouth', state: 'MN', region: 'Twin Cities West & South',
    phone: '763-509-5250',
    website: 'https://www.plymouthmn.gov/departments/parks-recreation/ice-center/open-skate-open-hockey',
    note: 'Open skating year-round, plus open hockey.',
  },
  {
    id: 'braemar-edina',
    name: 'Braemar Arena',
    town: 'Edina', state: 'MN', region: 'Twin Cities West & South',
    website: 'https://www.edinamn.gov/492/Open-Skating',
    note: 'Open skating and open hockey; register through the city site.',
  },
  {
    id: 'hopkins-pavilion',
    name: 'Hopkins Pavilion',
    town: 'Hopkins', state: 'MN', region: 'Twin Cities West & South',
    website: 'https://www.hopkinsmn.com/192/Open-Skate',
  },
  {
    id: 'ramsey-county-arenas',
    name: 'Ramsey County arenas',
    town: 'Ramsey County', state: 'MN', region: 'Minneapolis & St. Paul',
    website: 'https://www.ramseycountymn.gov/residents/parks-recreation/ice-arenas-fieldhouse/skating-programs/open-skate',
    note: 'Free open skating at several county arenas; dates are on the county calendar (search "Open Skate").',
  },
];
